using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Shards.Bots;

namespace SoiSim
{
    /// <summary>Regenerates Assets/Scripts/Shards/Bots/ShardsEvalWeights.g.cs with every
    /// existing vector (found via reflection on the compiled ShardsEvalWeights) plus the
    /// newly tuned one, Current pointing at the newest. Old vectors stay — they anchor
    /// the tuner's reference pool and the strength reports.</summary>
    public static class WeightsEmitter
    {
        public static string DefaultPath =>
            Path.Combine(SimConfig.FindRepoRoot(), "Assets", "Scripts", "Shards", "Bots", "ShardsEvalWeights.g.cs");

        public static List<(string Name, double[] Vector)> ExistingVectors()
        {
            return typeof(ShardsEvalWeights)
                .GetFields(BindingFlags.Public | BindingFlags.Static)
                .Where(f => f.FieldType == typeof(double[]))
                .Select(f => (f.Name, (double[])f.GetValue(null)))
                .OrderBy(v => VersionNumber(v.Name))
                .ToList();
        }

        public static string NextVersionName()
        {
            int max = ExistingVectors().Select(v => VersionNumber(v.Name)).DefaultIfEmpty(0).Max();
            return "V" + (max + 1);
        }

        private static int VersionNumber(string name) =>
            name.Length > 1 && name[0] == 'V' && int.TryParse(name.Substring(1), out int n) ? n : 0;

        public static void Emit(string path, double[] tuned, string versionName, string provenance)
        {
            var vectors = ExistingVectors();
            vectors.RemoveAll(v => v.Name == versionName);
            vectors.Add((versionName, tuned));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Tuned weight vectors for the SoI value model. Regenerate with:");
            sb.AppendLine("//   dotnet run -c Release --project Tools/SoiSim -- tune …");
            sb.AppendLine("// " + provenance);
            sb.AppendLine("// Keep superseded vectors — they anchor the tuner's reference pool.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("namespace Shards.Bots");
            sb.AppendLine("{");
            sb.AppendLine("    public static class ShardsEvalWeights");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>The vector new bots use by default.</summary>");
            sb.AppendLine($"        public static double[] Current => {versionName};");
            foreach (var (name, vector) in vectors)
            {
                sb.AppendLine();
                sb.AppendLine($"        public static readonly double[] {name} =");
                sb.AppendLine("        {");
                for (int i = 0; i < vector.Length; i += 6)
                {
                    var chunk = vector.Skip(i).Take(6)
                        .Select(v => v.ToString("0.0#####", CultureInfo.InvariantCulture));
                    sb.AppendLine("            " + string.Join(", ", chunk) + (i + 6 < vector.Length ? "," : ""));
                }
                sb.AppendLine("        };");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
            Console.WriteLine($"  emitted {versionName} ({tuned.Length} weights) -> {path}");
        }
    }
}
