'use strict';
const $=id=>document.getElementById(id), el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
const FIELDS=['name','faction','type','cost','quantity','defense','shield','rules_text','notes','art_id'];
const FORM={name:'edit-name',faction:'edit-faction',type:'edit-type',cost:'edit-cost',quantity:'edit-quantity',defense:'edit-defense',shield:'edit-shield',rules_text:'edit-rules',notes:'edit-notes',art_id:'edit-art'};
const RESPONSE={accepted:'Accepted in previous review',requested:'Updated from your request',new:'New design',retained:'Retained',rejected:'Excluded'};
let proposal,review,cardReviewScopes={},previewData={proposals:{}},catalog={cards:[],heroes:[]},draftDoc={schema:'shards-card-drafts-v1',revision:0,cards:[],updated_at:null};
let view='proposals',activeProposal=null,activePair=0,dirty=false,running=false,blocked=false,submitRequested=false,timer,serial=0,conflictReview=null,conflictProposal=null,draftKey='',storageOK=true;
let editing=null,editorDirty=false,draftSaving=false,draftConflict=false,draftsAvailable=false,editorBackup=null,editorBaseRevision=0;
const editorKey='shards-card-editor-v1';
function implemented(){return proposal?.implementation?.status==='implemented'}
function reviewed(e){return !!e&&(e.decision!=='unreviewed'||!!e.comment.trim())}
function setStatus(text,error=false){$('save-status').textContent=text;$('save-status').style.color=error?'var(--rose)':'var(--mint)'}
function showError(text,conflict=false){$('error').hidden=false;$('error-text').textContent=text;$('retry').hidden=conflict;$('use-saved').hidden=!conflict;$('use-draft').hidden=!conflict||!!conflictProposal||!conflictReview}
function saveDraft(){if(!review||!draftKey)return;try{localStorage.setItem(draftKey,JSON.stringify({proposal_version:proposal.version,base_revision:review.revision,entries:review.entries,card_entries:review.card_entries,general_comment:review.general_comment,dirty:dirty||running||blocked,client_updated:new Date().toISOString()}))}catch(_){storageOK=false}}
function updateProgress(){if(!proposal)return;let count=0,total=0;for(const p of proposal.proposals){const pairs=pairsFor(p);total+=cardReviewScopes[p.id]?.length||pairs.length;pairs.forEach((pair,index)=>{if(reviewed(entryFor(p,index)))count++})}$('progress-label').textContent=`${count} / ${total} reviewed`;$('patch-count').textContent=total;$('general-count').textContent=review.general_comment.length.toLocaleString()+' / 20,000';$('draft-count').textContent=draftDoc.cards.length}
function changed(){serial++;dirty=true;submitRequested=false;review.submitted_at=null;$('ready').hidden=true;updateProgress();setStatus(blocked?'Save conflict · your draft is kept':'Unsaved review');saveDraft();clearTimeout(timer);timer=setTimeout(save,650)}
async function save(){
 if(running||blocked||!proposal)return;running=true;
 try{while((dirty||submitRequested)&&!blocked){const wantSubmit=submitRequested,sentAt=serial,payload={proposal_version:proposal.version,revision:review.revision,entries:structuredClone(review.entries),card_entries:structuredClone(review.card_entries),general_comment:review.general_comment,submit:wantSubmit};submitRequested=false;dirty=false;setStatus('Saving review…');saveDraft();let response,data;
  try{response=await fetch('/api/balance-reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});data=await response.json()}
  catch(_){dirty=true;submitRequested=wantSubmit&&sentAt===serial;setStatus('Not saved to disk · browser draft kept',true);showError('The server could not be reached. Retry saving, or export your workspace before leaving.');break}
  if(response.status===409){dirty=true;blocked=true;submitRequested=false;conflictReview=data.review||null;conflictProposal=data.proposal||(!data.review?true:null);setStatus('Save conflict · your draft is preserved',true);showError(data.code==='proposal_content_conflict'?'The proposal changed without a new version. Export your draft and tell me in chat so I can fix the version; saved feedback is preserved.':conflictProposal?'The proposal version changed. Export your draft, then load the current proposal. Previous feedback is preserved.':'Another tab saved a newer review. Your text is still here; load the saved review or explicitly save this draft instead.',true);break}
  if(!response.ok){dirty=true;submitRequested=false;setStatus('Review not saved',true);showError(data.error||'The server rejected this save.');break}
  review.revision=data.review.revision;review.updated_at=data.review.updated_at;review.submitted_at=sentAt===serial?data.review.submitted_at:null;if(sentAt!==serial)dirty=true;$('error').hidden=true;
  if(review.submitted_at&&!dirty){$('ready').textContent='Review saved and marked ready. Tell me “review ready” in chat; I’ll read your comments and card designs.';$('ready').hidden=false}
  setStatus(dirty?'Saving newer edits…':review.submitted_at?'Saved · ready for analysis':'All review changes saved');
 }}finally{running=false;saveDraft();if(!storageOK&&dirty)setStatus('Not saved · browser backup unavailable; export before leaving',true)}
}
function finish(){if(!proposal)return;if(blocked){$('error').scrollIntoView({block:'center'});return}clearTimeout(timer);submitRequested=true;save()}
function cardFace(c,old=null){
 if(!c){const n=el('div',undefined,'card-empty');n.append(el('b','+'),el('span','New card'),el('small',implemented()?'No previous version':'No current version'));return n}
 const n=el('div',undefined,'game-card');n.dataset.faction=c.faction||'None';const art=el('div',undefined,'card-art');
 const placeholder=()=>{const a=el('div',undefined,'concept-art');a.append(el('b',c.type==='Hero'?'♜':c.type==='Rule'?'◇':'✧'),el('span',c.type==='Rule'?'DUEL RULES':'CONCEPT ART'));return a};
 if(c.art_id){const img=el('img');img.src='/api/card-image?id='+encodeURIComponent(c.art_id);img.alt='';img.loading='lazy';img.onerror=()=>{img.remove();art.prepend(placeholder())};art.append(img)}else art.append(placeholder());
 const hideCost=['Hero','Rule','Relic','Destiny'].includes(c.type);if(c.cost!=null&&!hideCost){const cost=el('span',String(c.cost),'cost'+(old&&old.cost!==c.cost?' changed':''));cost.title='Cost: '+c.cost;art.append(cost)}n.append(art,el('div',c.name||'Untitled card','card-name'));
 n.append(el('div',[c.faction&&c.faction!=='None'?c.faction:null,c.type].filter(Boolean).join(' · '),'card-type'));
 const rules=el('div',undefined,'card-rules'),oldLines=(old?.rules_text||'').split('\n');(c.rules_text||'Write your card’s rules…').split('\n').forEach(line=>{if(!line)return;rules.append(el('div',line,old&&!oldLines.includes(line)?'changed-rule':undefined))});n.append(rules);
 const stats=el('div',undefined,'card-stats');for(const [key,label]of [['defense','Defense'],['shield','Shield'],['quantity','Copies']]){if(c[key]==null||(key!=='quantity'&&!c[key]))continue;stats.append(el('span',label+' '+c[key],old&&old[key]!==c[key]?'changed':''))}n.append(stats);return n;
}
function cardPair(pair,onClick){const n=el('div',undefined,'pair');for(const [label,c,old]of [[implemented()?'BEFORE':'CURRENT',pair.before,null],[implemented()?'AFTER':'PROPOSED',pair.after,pair.before]]){const slot=el('div',undefined,'pair-slot');slot.append(el('div',label,'version-label'+(label==='PROPOSED'||label==='AFTER'?' proposed':'')));if(onClick){const b=el('button',undefined,'card-button');b.type='button';b.setAttribute('aria-label',`Review ${c?.name||pair.after?.name||'new card'} — ${label.toLowerCase()}`);b.append(cardFace(c,old));b.onclick=onClick;slot.append(b)}else slot.append(cardFace(c,old));n.append(slot)}return n}
function pairsFor(p){return previewData.proposals[p.id]?.cards||[{before:{name:p.title,type:'Rule',faction:'None',rules_text:p.current},after:{name:p.title,type:'Rule',faction:'None',rules_text:p.proposed}}]}
function scopedReview(p){return !!cardReviewScopes[p.id]||pairsFor(p).length>1}
function entryFor(p,index=0){
 if(!scopedReview(p))return review.entries[p.id];
 const pair=pairsFor(p)[index],id=(pair?.after||pair?.before)?.id;
 // A missing/stale preview must never fall back to the old shared group entry.
 if(!id||!cardReviewScopes[p.id]?.includes(id))return null;
 review.card_entries[p.id]||={};return review.card_entries[p.id][id]||={decision:'unreviewed',comment:''};
}
function activeEntry(){const p=proposal?.proposals.find(p=>p.id===activeProposal);return p?entryFor(p,activePair):null}
function pairChanged(pair){const keys=['name','faction','type','cost','quantity','defense','shield','rules_text'];return !pair.before||!pair.after||keys.some(key=>pair.before[key]!==pair.after[key])}
function selectView(next){view=next;document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===next);b.setAttribute('aria-pressed',String(b.dataset.view===next))});$('filter').hidden=next!=='proposals';$('search').value='';renderGallery()}
function renderGallery(){
 if(!proposal)return;const g=$('gallery');g.replaceChildren();g.className='gallery'+(view==='drafts'?' draft-grid':view==='library'?' library-grid':'');const q=$('search').value.trim().toLowerCase();let count=0;
 if(view==='proposals'){
  const filter=$('filter').value;for(const p of proposal.proposals){const isKeep=p.kind==='keep';if(filter==='changes'&&isKeep||filter==='new'&&p.response?.status!=='new'||filter==='keep'&&!isKeep)continue;
   pairsFor(p).forEach((pair,index)=>{const entry=entryFor(p,index),has=reviewed(entry);if(filter==='reviewed'&&!has||filter==='unreviewed'&&has||filter==='changes'&&!pairChanged(pair))return;if(q&&!JSON.stringify([p.title,pair]).toLowerCase().includes(q))return;count++;const tile=el('article',undefined,'proposal-tile');tile.dataset.proposal=p.id;tile.dataset.card=(pair.after||pair.before)?.id||'';const top=el('div',undefined,'tile-top'),title=el('div');title.append(el('h2',pair.after?.name||p.title,'tile-title'),el('div',p.title,'tile-caption'));let badge=entry&&entry.decision!=='unreviewed'?entry.decision:!pair.before?'New card':!pairChanged(pair)?'Unchanged':'Changed';top.append(title,el('span',badge==='accept'?'Accepted':badge==='change'?'Revise':badge==='reject'?'Rejected':badge,'badge '+badge.toLowerCase().replace(' card','')));tile.append(top,cardPair(pair,()=>openReview(p.id,index)));
   const bottom=el('div',undefined,'tile-bottom'),comment=el('span',entry?.comment||RESPONSE[p.response?.status]||'Click a card to review',entry?.comment?'tile-review-snippet':'');const b=el('button','Review ↗','link-button');b.onclick=()=>openReview(p.id,index);bottom.append(comment,b);tile.append(bottom);g.append(tile)});
  }$('gallery-caption').textContent=`${count} card comparisons · ${implemented()?'before and implemented patch':'current and proposed'} side by side`;
 }else{
  const replaced=new Set(catalog.cards.map(c=>c.replaces_id).filter(Boolean));const source=view==='drafts'?draftDoc.cards:catalog.cards.filter(c=>!replaced.has(c.id));
  for(const c of source){if(q&&!JSON.stringify([c.name,c.faction,c.type,c.rules_text]).toLowerCase().includes(q))continue;count++;const tile=el('article',undefined,'single-tile'),b=el('button',undefined,'card-button');b.setAttribute('aria-label',(view==='drafts'?'Edit ':'Create from ')+c.name);b.append(cardFace({...c,art_id:c.art_id??c.id}));b.onclick=()=>openEditor(c,view==='drafts');const meta=el('div',undefined,'single-meta');meta.append(el('span',view==='drafts'?'Saved source design':implemented()?'Pre-patch reference card':'Current Duel card'));const copy=el('button',view==='drafts'?'Edit draft':'Use as template');copy.onclick=b.onclick;meta.append(copy);tile.append(b,meta);g.append(tile)}
  $('gallery-caption').textContent=view==='drafts'?`${count} saved card designs · ${implemented()?'retained for future edits':'awaiting implementation'}`:`${count} ${implemented()?'pre-patch reference':'current'} cards · click to create a design from one`;
 }$('empty').hidden=count!==0;document.querySelector('.legend').hidden=view!=='proposals';updateProgress();
}
function openReview(id,index=0){
 const p=proposal.proposals.find(p=>p.id===id);if(!p)return;activeProposal=id;activePair=pairsFor(p)[index]?index:0;const pair=pairsFor(p)[activePair],entry=entryFor(p,activePair);$('review-title').textContent=pair.after?.name||p.title;$('review-category').textContent=p.title;$('review-cards').replaceChildren(cardPair(pair));$('review-change').replaceChildren(el('h3',implemented()?'The implemented change':'The proposed change'),el('p',p.proposed,'change-callout'));
 if(scopedReview(p))$('review-change').append(el('p',entry?'Your review and decision apply only to this card.':'Card previews could not be loaded. Reload the page to review each card separately.','muted small'));
 for(const [title,items]of [['Implemented interaction rules',p.implemented_notes],[implemented()?'Design notes from the review':'Interaction rules for review',p.design_notes],['Setup procedure',p.implementation_notes]]){if(!items?.length)continue;const details=el('details',undefined,'detail-block');details.append(el('summary',title));const list=el('ol');items.forEach(text=>list.append(el('li',text)));details.append(list);details.open=p.group==='combat-designs';$('review-change').append(details)}
 $('review-decision').disabled=!entry;$('review-comment').disabled=!entry;$('review-decision').value=entry?.decision||'unreviewed';$('review-comment').value=entry?.comment||'';$('comment-count').textContent=(entry?.comment.length||0).toLocaleString()+' / 10,000';$('previous-feedback').replaceChildren();
 const legacy=review.entries[id];if(scopedReview(p)&&reviewed(legacy)){const box=el('div',undefined,'previous-feedback legacy-group-feedback');box.append(el('strong','Earlier shared review (preserved)'),el('p','This feedback was saved for the whole proposal group. It is kept here as context; the individual card reviews above are separate.'));if(legacy.decision!=='unreviewed')box.append(el('p','Earlier group decision: '+legacy.decision));if(legacy.comment)box.append(el('blockquote',legacy.comment));$('previous-feedback').append(box)}
 if(p.response){const box=el('div',undefined,'previous-feedback');box.append(el('strong',RESPONSE[p.response.status]||'Your previous review'));if(p.response.comment)box.append(el('blockquote',p.response.comment));box.append(el('p',p.response.explanation));$('previous-feedback').append(box)}
 const evidence=$('review-evidence');evidence.replaceChildren(el('p',p.reason));for(const [title,items]of [['Evidence',p.evidence],['What to check',p.watch]]){if(!items?.length)continue;evidence.append(el('strong',title));const ul=el('ul');items.forEach(t=>ul.append(el('li',t)));evidence.append(ul)}
 if(p.sources?.length){evidence.append(el('strong','Sources'));const list=el('ul');for(const source of p.sources){if(!/^https?:\/\//.test(source.url))continue;const item=el('li'),link=el('a',source.title);link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';item.append(link);list.append(item)}evidence.append(list)}
 const links=$('review-interactions');links.replaceChildren();if(p.interactions?.length)links.append(el('h3','Linked changes'));for(const i of p.interactions||[]){const target=proposal.proposals.find(p=>p.id===i.id);if(!target)continue;const line=el('p',undefined,'interaction'),a=el('a',target.title);a.href='#'+target.id;a.onclick=e=>{e.preventDefault();openReview(target.id)};line.append(a,document.createTextNode(' — '+i.text));links.append(line)}
 $('customize-proposal').textContent=implemented()?'Use this card in editor':'Use proposed card in editor';$('customize-proposal').disabled=!pair.after||pair.after.type==='Rule';$('customize-proposal').onclick=()=>{const c={...pair.after,source_proposal_id:id};$('review-dialog').close();openEditor(c,false)};
 history.replaceState(null,'','#'+id);if(!$('review-dialog').open)$('review-dialog').showModal();
}
function closeReview(){$('review-dialog').close();history.replaceState(null,'',location.pathname);renderGallery()}
function patchNotes(){const n=$('patch-notes');n.replaceChildren();const notes=proposal.patch_notes;if(!notes){n.append(el('p',proposal.summary));return}if(notes.status)n.append(el('p',notes.status,'change-callout'));for(const [title,rows]of [['Reviewed card and hero changes',notes.changes],[implemented()?'New cards':'New card designs',notes.new_designs],['New rules',notes.rules],[implemented()?'Champion interactions':'Champion interaction proposals',notes.combat_designs]]){if(!rows?.length)continue;n.append(el('h3',title));const ul=el('ul');for(const r of rows){const li=el('li'),a=el('a',r.title);a.href='#'+r.id;a.onclick=e=>{e.preventDefault();$('package-dialog').close();openReview(r.id)};li.append(a,document.createTextNode(' — '+r.detail));ul.append(li)}n.append(ul)}if(notes.package_notes){n.append(el('h3','Interactions'));const ul=el('ul');notes.package_notes.forEach(t=>ul.append(el('li',t)));n.append(ul)}}
function blankCard(){return {id:'draft-'+crypto.randomUUID(),name:'',faction:'Order',type:'Ally',cost:2,quantity:2,defense:0,shield:0,rules_text:'',notes:'',art_id:'',source_proposal_id:''}}
function formValue(){const c={...editing};for(const key of FIELDS){const value=$(FORM[key]).value;c[key]=['cost','quantity','defense','shield'].includes(key)?Number(value):value}return c}
function storeEditor(){if(!editing)return;const value=formValue();try{localStorage.setItem(editorKey,JSON.stringify({card:value,base_revision:editorBaseRevision,dirty:editorDirty}));editorBackup={card:value,base_revision:editorBaseRevision,dirty:editorDirty}}catch(_){}$('editor-recovery').hidden=!editorDirty}
function previewEditor(){if(!editing)return;$('live-preview').replaceChildren(cardFace(formValue()));}
function openEditor(c=null,existing=false,recover=false){
 if(!draftsAvailable){showError('Saved card designs are unavailable. Reload before editing so existing designs can be preserved.');return}
 if((editorDirty||editorBackup?.dirty)&&!recover){if(editorDirty&&editing)storeEditor();if(!confirm('There is an unfinished card in the editor. Replace it with this design?'))return;try{localStorage.removeItem(editorKey)}catch(_){}editorBackup=null;$('editor-recovery').hidden=true}
 let base=blankCard();if(c){for(const key of FIELDS)if(c[key]!=null)base[key]=c[key];base.art_id=c.art_id??(c.id&&catalog.cards.some(x=>x.id===c.id)?c.id:'');base.source_proposal_id=c.source_proposal_id||'';if(existing||recover)base.id=c.id}
 editorBaseRevision=recover?(editorBackup?.base_revision??draftDoc.revision):draftDoc.revision;editing=base;editorDirty=recover;draftConflict=false;for(const key of FIELDS)$(FORM[key]).value=base[key];$('editor-title').textContent=existing?'Edit card proposal':'Create a card';$('delete-card').hidden=!draftDoc.cards.some(x=>x.id===base.id);$('editor-error').hidden=true;$('save-card').disabled=false;$('editor-status').textContent='Saving stores a proposal for implementation later.';previewEditor();if(!$('editor-dialog').open)$('editor-dialog').showModal();
}
function closeEditor(){if(draftSaving)return;if(editorDirty)storeEditor();$('editor-dialog').close();$('editor-recovery').hidden=!editorDirty}
async function saveCard(event){event?.preventDefault();if(!editing||draftSaving||!$('card-form').reportValidity())return;const c=formValue();if(!c.name.trim()){showEditorError('Give this card a name before saving.');return}const cards=draftDoc.cards.filter(x=>x.id!==c.id);cards.push(c);await publishCards(cards,c,false)}
function showEditorError(text){$('editor-error').hidden=false;$('editor-error').replaceChildren(el('span',text));}
async function publishCards(cards,c,deleting){
 draftSaving=true;editorDirty=true;storeEditor();$('save-card').disabled=true;$('delete-card').disabled=true;for(const id of Object.values(FORM))$(id).disabled=true;$('editor-status').textContent='Saving card proposal…';
 try{const response=await fetch('/api/card-drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:editorBaseRevision,cards})});const data=await response.json();
  if(response.status===409&&data.draft){draftDoc=data.draft;editorBaseRevision=data.draft.revision;draftConflict=true;storeEditor();showEditorError('Another tab changed the saved card designs. Your editor text is preserved. Save again to apply this card to the updated collection.');$('editor-status').textContent='Conflict found · no card was overwritten';return}
  if(!response.ok)throw Error(data.error||'Card save failed');draftDoc=data;draftsAvailable=true;editorDirty=false;editorBackup=null;try{localStorage.removeItem(editorKey)}catch(_){}$('editor-recovery').hidden=true;$('editor-dialog').close();editing=null;selectView('drafts');setStatus(deleting?'Card draft deleted · earlier version kept':'Card proposal saved for implementation later');
 }catch(error){showEditorError(error.message+'. Your editor draft is kept in this browser.');$('editor-status').textContent='Not saved to disk'}finally{draftSaving=false;$('save-card').disabled=false;$('delete-card').disabled=false;for(const id of Object.values(FORM))$(id).disabled=false;updateProgress()}
}
async function deleteCard(){if(!editing||draftSaving)return;if(!confirm('Delete this saved card proposal? Its previous saved version remains recoverable.'))return;await publishCards(draftDoc.cards.filter(c=>c.id!==editing.id),editing,true)}
async function jsonGet(path){const response=await fetch(path),data=await response.json();if(!response.ok)throw Error(data.error||'Cannot load '+path);return data}
async function load(){
 try{const data=await jsonGet('/api/balance-proposals');proposal=data.proposal;review=data.review;review.card_entries||={};cardReviewScopes=data.card_review_scopes||{};draftKey='shards-balance-review:'+proposal.version;
  const results=await Promise.allSettled([jsonGet('/api/balance-card-previews'),jsonGet('/api/card-catalog'),jsonGet('/api/card-drafts')]);
  if(results[0].status==='fulfilled'&&results[0].value.proposal_version===proposal.version)previewData=results[0].value;
  if(results[1].status==='fulfilled')catalog=results[1].value;
  if(results[2].status==='fulfilled'){draftDoc=results[2].value;draftsAvailable=true}else{showError('Saved card designs could not be loaded. Existing designs will not be overwritten. Reload the page to retry.');$('create-card').disabled=true}
  let local;try{local=JSON.parse(localStorage.getItem(draftKey)||'null');editorBackup=JSON.parse(localStorage.getItem(editorKey)||'null')}catch(_){storageOK=false}
  if(local?.dirty&&local.proposal_version===proposal.version&&Object.keys(local.entries||{}).every(id=>proposal.proposals.some(p=>p.id===id))){if(local.base_revision!==review.revision){conflictReview=structuredClone(review);blocked=true}review.entries=local.entries;if(local.card_entries)review.card_entries=local.card_entries;review.general_comment=local.general_comment||'';review.submitted_at=null;dirty=true}
  for(const p of proposal.proposals)review.entries[p.id]||={decision:'unreviewed',comment:''};
  const artOptions=[...catalog.cards,...catalog.heroes].sort((a,b)=>a.name.localeCompare(b.name));for(const c of artOptions){const o=el('option',c.name);o.value=c.id;$('edit-art').append(o)}
  $('version').textContent=(implemented()?'Patch ':'Proposal ')+proposal.version;$('patch-eyebrow').textContent=implemented()?'IMPLEMENTED DUEL PATCH':'THE NEXT DUEL PATCH';$('patch-summary').textContent=proposal.summary;$('implementation-status').textContent=implemented()?'Implemented in Duel · statistics remain pre-patch':'Drafts only · nothing applied to the game';document.querySelector('.legend-current').textContent=implemented()?'BEFORE':'CURRENT';document.querySelector('.legend-new').textContent=implemented()?'AFTER':'PROPOSED';if(implemented())$('footer-note').textContent='Earlier reviews and source designs are preserved. New feedback and editor changes are proposals for a future patch.';$('patch-count').textContent=proposal.proposals.length;$('general-comment').value=review.general_comment;$('editor-recovery').hidden=!editorBackup?.dirty;
  $('retry').textContent='Retry saving';$('retry').onclick=save;patchNotes();renderGallery();
  if(blocked){setStatus('Recovered draft · saved review also changed',true);showError('A browser draft was recovered, but another review was saved. Choose which review to keep.',true)}else if(dirty)save();else setStatus(review.submitted_at?'Saved · ready for analysis':'Reviews and card designs loaded');
  if(review.submitted_at){$('ready').textContent='This review is marked ready. Tell me in chat when you want me to analyze your latest feedback and card designs.';$('ready').hidden=false}
  const hash=decodeURIComponent(location.hash.slice(1));if(hash==='patch-notes')$('package-dialog').showModal();else if(proposal.proposals.some(p=>p.id===hash))openReview(hash);
 }catch(error){setStatus('Could not load the workshop',true);showError(error.message);$('retry').textContent='Retry loading';$('retry').onclick=load}
}
$('search').oninput=renderGallery;$('filter').onchange=renderGallery;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>selectView(b.dataset.view));
$('review-comment').oninput=()=>{const entry=activeEntry();if(!entry)return;entry.comment=$('review-comment').value;$('comment-count').textContent=$('review-comment').value.length.toLocaleString()+' / 10,000';changed()};$('review-decision').onchange=()=>{const entry=activeEntry();if(entry){entry.decision=$('review-decision').value;changed()}};
$('close-review').onclick=closeReview;$('review-dialog').addEventListener('cancel',()=>{history.replaceState(null,'',location.pathname);renderGallery()});
$('package-button').onclick=()=>$('package-dialog').showModal();$('close-package').onclick=()=>$('package-dialog').close();$('general-comment').oninput=()=>{review.general_comment=$('general-comment').value;changed()};$('finish').onclick=finish;$('finish-bottom').onclick=finish;
$('use-saved').onclick=()=>{if(!confirm('Replace this tab’s unsaved review with the saved review? Export first to keep both.'))return;try{localStorage.removeItem(draftKey)}catch(_){}dirty=false;blocked=false;location.reload()};$('use-draft').onclick=()=>{if(!conflictReview)return;review.revision=conflictReview.revision;blocked=false;dirty=true;conflictReview=null;$('error').hidden=true;save()};
$('create-card').onclick=()=>{if(draftsAvailable)openEditor()};$('close-editor').onclick=closeEditor;$('editor-dialog').addEventListener('cancel',e=>{e.preventDefault();closeEditor()});$('card-form').onsubmit=saveCard;$('delete-card').onclick=deleteCard;
for(const id of Object.values(FORM))$(id).addEventListener('input',()=>{editorDirty=true;previewEditor();storeEditor()});
$('resume-editor').onclick=()=>{if(editorBackup?.card){openEditor(editorBackup.card,draftDoc.cards.some(c=>c.id===editorBackup.card.id),true)}};
$('discard-editor').onclick=()=>{if(!confirm('Discard the unfinished browser draft? Saved cards are kept.'))return;try{localStorage.removeItem(editorKey)}catch(_){}editorBackup=null;editing=null;editorDirty=false;$('editor-recovery').hidden=true};
$('export').onclick=()=>{if(!proposal)return;const value={proposal,review:{...structuredClone(review),has_unsaved_changes:dirty||running||blocked},card_designs:draftDoc,unfinished_card:editing&&editorDirty?formValue():editorBackup?.dirty?editorBackup.card:null,exported_at:new Date().toISOString()},url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)+'\n'],{type:'application/json'})),a=el('a');a.href=url;a.download='shards-workshop-'+proposal.version+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
window.addEventListener('beforeunload',e=>{if(dirty||running||blocked||editorDirty||draftSaving){saveDraft();if(editorDirty)storeEditor();e.preventDefault();e.returnValue=''}});window.addEventListener('pagehide',()=>{saveDraft();if(editorDirty)storeEditor()});window.addEventListener('online',()=>{if(dirty&&!blocked)save()});load();
