"""CPU-only Chromium checks for the standalone statistics gallery; no live games."""
from pathlib import Path
import os
import subprocess
import tempfile
import unittest

HERE = Path(__file__).resolve().parent
CHROME = Path(os.environ.get('CHROMIUM_BINARY', str(Path.home()/'.cache/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell')))
HARNESS = r'''<script>
try {
 let checks=0;const check=(x,m)=>{if(!x)throw Error(m);checks++},tab=v=>$('tabs').querySelector('[data-view="'+v+'"]').click(),change=(id,v)=>{$(id).value=v;$(id).dispatchEvent(new Event('change'))};
 const hero={id:'tetra',name:'Tetra',games:40,wins:22,draws:0,losses:18,score:.55,score_bound_95:[.2,.9]},base={state:'ready',snapshot_id:'fixture',scope:{label:'Training pool',policy_label:'Both players',policy_versions:[],sample_unit:'Correlated player-games',confidence_method:'Supplied cluster interval'},refresh:{every_games:10000,games_since_snapshot:null,evaluation_sample_count:0},totals:{attempted_games:40,resolved_games:39,censored_games:1,draws:0,seat0_wins:19,mean_rounds:12},rankings:{heroes:[hero,{id:'rez',name:'Rez',games:0,score:null,score_bound_95:null}],cards:[],relics:[],destinies:[]},hero_matchups:[{hero_a:'tetra',hero_b:'rez',games:20,wins:12,draws:0,losses:8,score:.6,score_bound_95:[.1,1]}],hero_seats:[],hero_choice_rows:[],insights:['Actual test observation']};
 base.rankings.cards=Array.from({length:30},(_,i)=>({id:'card'+i+':buy',card_id:i+1,name:'Card '+String(i).padStart(2,'0'),type:'Ally',set:i%2?'duel':'base',choice_kind:'buy',games:100-i,wins:50-i,draws:0,losses:50,score:(50-i)/(100-i),score_bound_95:[0,1],pick_count:110-i,pick_rate:null,opportunities:null}));
 base.rankings.cards.push({id:'unknown',name:'Unknown <img src=x onerror=alert(1)>',type:'Ally',set:'base',games:10,wins:5,draws:0,losses:5,score:null,censored_games:1,score_identification_interval:[5/11,6/11],score_bound_95:[0,1]});
 base.hero_choice_rows=[{...base.rankings.cards[0],id:'card0:buy:tetra',hero_id:'tetra',games:22,wins:2,losses:20,score:2/22}];
 const frozen={...base,scope:{...base.scope,label:'Frozen evaluation',policy_label:'Learner',policy_versions:[123]},hero_choice_rows:undefined};
 const data={wall:1780000010,catalog:{cards:[{id:'card0',image_url:'/api/card-image?id=card0',rules_text:'Draw one card.',faction:'Homodeus',cost:3}],heroes:[{id:'tetra',image_url:'/api/card-image?id=tetra'}]},balance_statistics_sources:{training_random:null,training_natural:null,training_pool:base,frozen},balance_statistics_error:null};
 render(data);check(currentSource==='training_pool','ready pool fallback');check($('cadence').textContent.includes('10,000 completed games in this source')&&!$('cadence').textContent.includes('frozen matches'),'pool cadence units');check($('cadence').textContent.includes('next update after another batch'),'unknown cadence progress not zero');check($('policyScope').textContent.includes('changing policies'),'no unknown version falsely presented');check($('results').querySelectorAll('.entry').length===2,'zero-coverage heroes discoverable by default');check($('results').textContent.includes('No outcomes'),'unseen hero not low win rate');
 tab('cards');check($('results').querySelectorAll('.entry').length===24,'gallery caps lazy images at24');check(!$('pagination').hidden,'pagination visible');check(document.querySelector('#results img').getAttribute('loading')==='lazy','images lazy');check(document.querySelector('#results img').src.includes('card0'),'catalog uses definition ID, not numeric card_id');check(document.querySelector('#results .entry').textContent.includes('Homodeus'),'catalog metadata fallback');
 document.querySelector('#results .art-button').click();check($('detail').open&&$('detailCopy').textContent.includes('Draw one card.'),'image opens rules detail');check($('detailCopy').textContent.includes('Cost 3'),'detail real card cost');$('detail').close();
 $('next').click();check($('results').querySelectorAll('.entry').length===7,'lastpage entries');check($('results').textContent.includes('Unknown')&&$('results').textContent.includes('1 unresolved · not draws'),'censor unknown displayed');check($('results').textContent.includes('Unknown-outcome range'),'censor interval preserved');check(!$('results').querySelector('[onerror]'),'card names are text, no injected HTML');
 change('hero','tetra');check(filtered.length===31,'hero filter preserves unobserved catalog choices');check(filtered.find(r=>r.id==='card0:buy:tetra').games===22&&$('results').textContent.includes('9.1%'),'hero-specific outcome used');const unseenHero=filtered.find(r=>r.id==='card1:buy:tetra');check(unseenHero.games===0&&unseenHero.wins===0&&unseenHero.losses===0&&unseenHero.pick_count===0&&unseenHero.score===null&&unseenHero.mean_acquisition_round===null,'unobserved hero row never borrows global outcome or event counts');tab('relics');check($('results').textContent.includes('No observations published here yet'),'no synthetic hero/category fallback');
 tab('cards');change('hero','__all__');change('expansion','duel');check(filtered.length===15,'expansion filter');change('minimum','100');check(filtered.length===0&&$('results').textContent.includes('No entries match'),'filter empty reason');document.querySelector('#results button').click();check(filtered.length===31,'reset filters recovers all');
 change('source','frozen');check($('hero').disabled,'unsupported per-hero disabled');check(mode({choice_kind:'fastplay'})==='Fast-play entry','frozen fastplay makes no temporary ownership claim');check($('metrics').textContent.includes('Mean observed rounds')&&$('metrics').textContent.includes('Latest pre-action observation'),'frozen round estimate labeled');check($('interpretation').textContent.includes('not the exact terminal round')&&$('interpretation').textContent.includes('can later become permanent'),'frozen timing and retention semantics explicit');data.balance_statistics_sources.training_random=base;render(data);check(currentSource==='frozen','explicit user source remains');pinned=false;render(data);check(currentSource==='training_random','ready random cohort preferred');
 tab('hero_matchups');check($('results').textContent.includes('Tracked player ↓ / opponent →'),'pool matchup roles');check($('results').textContent.includes('60%'),'matchup score');change('source','frozen');check($('results').textContent.includes('Learner ↓ / opponent →'),'frozen matchup roles');
 tab('cards');$('tableView').click();check($('results').querySelectorAll('tbody tr').length===24,'table paginates too');check($('results').textContent.includes('menus'),'frozen exposure distinguished');check(imageUrl({image_url:'https://outside.example/image.png'})===null&&imageUrl({image_url:'//outside.example/image.png'})===null,'external assets blocked');
 data.balance_statistics_error='Rejected incompatible source';render(data);check(!$('error').hidden&&$('error').textContent.includes('Rejected'),'publication errors visible');check($('confidence').textContent==='Supplied cluster interval','uncertainty exact supplied method');
 const old={id:'old_relic:relic',name:'Old relic',type:'Relic',choice_kind:'relic',games:0},fresh={id:'new_relic:relic',name:'New relic',type:'Relic',choice_kind:'relic',games:0};base.rankings.relics=[old,fresh];data.catalog.cards.push({id:'old_relic',name:'Old relic',type:'Relic'},{id:'new_relic',name:'New relic',type:'Relic',replaces_id:'old_relic'});change('source','training_pool');render(data);tab('relics');change('availability','active');check(filtered.length===1&&filtered[0].id==='new_relic:relic','active but unobserved relic remains; replaced relic hidden');check($('resultSummary').textContent.includes('1 unavailable'),'hidden catalog count disclosed');change('availability','all');check(filtered.length===2&&$('results').textContent.includes('Replaced by New relic'),'all catalog entries explains replacement');$('gridView').click();[...$('results').querySelectorAll('.entry')].find(n=>n.textContent.includes('Old relic')).querySelector('button').click();check($('detailCopy').textContent.includes('Replaced by New relic'),'replacement explanation in detail');$('detail').close();base.rankings.cards.push({id:'starter:buy',name:'Starter',type:'Starter',choice_kind:'buy',games:0});tab('cards');change('availability','active');check(!filtered.some(r=>r.id==='starter:buy'),'nonpurchasable starter hidden');change('availability','all');check(filtered.some(r=>r.id==='starter:buy'),'nonpurchasable starter inspectable');
 data.catalog.cards.push({id:'cloud_oracles',name:'Cloud Oracles',type:'Ally'},{id:'cloud_oracles_sos',name:'Cloud Oracles',type:'Ally'});base.rankings.cards.push({id:'cloud_oracles:buy',name:'Cloud Oracles',type:'Ally',choice_kind:'buy',games:0},{id:'cloud_oracles_sos:buy',name:'Cloud Oracles',type:'Ally',choice_kind:'buy',games:2});render(data);change('availability','active');check(!filtered.some(r=>r.id==='cloud_oracles:buy')&&filtered.some(r=>r.id==='cloud_oracles_sos:buy'),'special SoS Cloud Oracles replacement respected');
 base.rankings.relics.push({id:'tetra_relic:relic',name:'Tetra relic',type:'Relic',character:'tetra',choice_kind:'relic',games:50,wins:40,draws:0,losses:10,score:.8,pick_count:60,mean_acquisition_round:9},{id:'rez_relic:relic',name:'Rez relic',type:'Relic',character:'rez',choice_kind:'relic',games:60,wins:50,draws:0,losses:10,score:5/6,pick_count:70});change('source','training_pool');render(data);tab('relics');change('hero','tetra');check(filtered.length===1&&filtered[0].id==='tetra_relic:relic:tetra','hero relic scaffold excludes foreign and unassigned relics');check(filtered[0].games===0&&filtered[0].pick_count===0&&filtered[0].score===null&&filtered[0].mean_acquisition_round===null,'missing eligible relic shown as unknown with zero own acquisitions');
 render({wall:1780000011,balance_statistics_sources:{}});check($('results').textContent.includes('Waiting for the first snapshot'),'empty awaiting state');
 render(data);pinned=false;render(data);tab('heroes');$('gridView').click();check(document.documentElement.scrollWidth<=window.innerWidth,'responsive viewport no horizontal overflow');
 const finalData={...data,balance_statistics_sources:{final:{...base,scope:{...base.scope,label:'Final frozen evaluation',final_evaluation:true,policy_versions:[18232]},totals:{...base.totals,attempted_games:50000,resolved_games:50000}}}};render(finalData);check(currentSource==='final'&&$('source').options.length===1&&$('source').disabled,'final evaluation is the only selectable dataset');check($('metrics').textContent.includes('50,000'),'exact final completed-game count visible');

 tab('strategies');check($('results').textContent.includes('Strategy capture is being prepared'),'old dataset does not invent strategies');
 const sr={id:'setup-test',category:'builds',hero_id:'tetra',name:'Measured winning build',description:'Normal selections only',image_ids:['tetra','card0'],games:30,wins:18,draws:0,losses:12,score:.6,win_share:.18,mean_winning_rounds:10,mean_winning_mastery:20,seat0_games:15,seat0_wins:10,seat1_games:15,seat1_wins:8,supporting_cards:[{id:'card0',winning_presence:.5}]};
 finalData.balance_statistics_sources.final.strategies={state:'ready',games:50000,rows:[sr,{...sr,id:'rare',name:'Tiny sample',games:1,wins:1,score:1},{...sr,id:'pattern',category:'patterns',name:'Champion engine',hero_id:null}]};
 render(finalData);check($('results').textContent.includes('No strategies meet'),'default minimum guards rare strategy claims');strategyMinimum=20;renderStrategies();check($('results').querySelectorAll('.strategy-card').length===1,'strategy sample filter');check($('results').textContent.includes('18')&&$('results').textContent.includes('60%'),'strategy wins and score displayed');check($('results').querySelectorAll('.strategy-faces img').length===2,'joint strategy has card and hero images');document.querySelector('.strategy-faces button').click();check($('detail').open,'strategy image opens card details');$('detail').close();strategyCategory='patterns';renderStrategies();check($('results').textContent.includes('Champion engine'),'play patterns available');tab('heroes');check(!document.querySelector('.filters').hidden&&!$('gridView').disabled,'normal filters restored after strategies');tab('strategies');check(document.documentElement.scrollWidth<=window.innerWidth,'strategy view fits viewport');

 tab('balance');check($('results').textContent.includes('No finishing causes are inferred'),'old snapshot does not invent victory causes');
 const bd={count:30,mean:12,median:12,p10:10,p90:14,histogram:[{value:10,count:10},{value:12,count:10},{value:14,count:10}]};
 const bg={games:60,wins:29,draws:2,score:.5,victory:{mastery:10,comet:1,normal_damage:18},rounds:bd,winning_health:bd,winning_mastery:bd,metrics:[{id:'gems_gained',name:'Gems gained',total:200,per_player_game:3.33,per_turn:1,in_wins:4}],milestones:[{id:'mastery30_round',name:'Mastery 30',games:12,reach_rate:.2,mean_round:10,wins:10,score:10/12}],cards:[{id:'card0',acquired_games:25,acquired_wins:15,acquired_draws:0,acquired_count:30,acquired_used_games:20,acquired_score:.6,use_rate:.8,mean_first_acquisition_round:5,played_count:40,fast_count:0,activated_count:0,deployed_count:0,banished_count:3,rerolled_count:10}],destiny_sources:[{id:'card0',source:'normal',games:10,wins:6,score:.6,mean_round:5},{id:'card0',source:'reward',games:3,wins:3,score:1,mean_round:11}],modes:[{id:'tetra|Gain 2 gems',games:10,wins:6,count:20,score:.6}]};
 const ba={state:'ready',games:30,victory:['mastery','comet','normal_damage','other_health_loss','concession','unknown','draw'].map(id=>({id,name:id,count:id==='draw'?1:0})),groups:{},rounds:bd,comet:{market_games:10,acquiring_players:2,acquirer_wins:1,playing_players:1,acquired_unplayed_players:1,finishing_wins:1,finishing_without_winner_play:0,acquisition_to_play_rounds:bd},definitions:['Definition test']};
 for(const h of ['all','tetra','rez'])for(const seat of ['all','0','1'])ba.groups[h+':'+seat]={...bg,games:h==='all'?60:30};
 finalData.balance_statistics_sources.final.balance_analysis=ba;render(finalData);
 check($('results').querySelectorAll('.balance-win').length===3,'three primary victory causes');check($('results').querySelector('[data-cause="mastery"]').textContent.includes('10'),'mastery finishing count displayed');check($('results').textContent.includes('Concession')||$('results').textContent.includes('concession'),'other causes visible');
 check($('results').querySelector('.balance-histogram')&&$('results').textContent.includes('Mastery 30'),'pacing chart and milestones');
 const bh=$('results').querySelector('[aria-label="Balance hero"]');bh.value='tetra';bh.dispatchEvent(new Event('change'));check($('resultSummary').textContent.includes('30 filtered player outcomes'),'balance hero filter uses matching cohort');
 const bs=$('results').querySelector('[aria-label="Balance seat"]');bs.value='1';bs.dispatchEvent(new Event('change'));check(balanceSeat==='1','balance seat filter');
 balancePanel='cards';renderBalance();check($('results').textContent.includes('80%')&&$('results').querySelector('.thumb img'),'card use rates and image displayed');$('results').querySelector('.thumb').click();check($('detail').open,'balance card opens details');$('detail').close();
 let exportRecord;const oldDownload=balanceDownload;balanceDownload=(...args)=>exportRecord=args;[...$('results').querySelectorAll('button')].find(b=>b.textContent==='Export filtered cards CSV').click();check(exportRecord[2]&&exportRecord[1].includes('acquired_used_games')&&exportRecord[1].includes('card0'),'CSV exports current filtered evidence');balanceDownload=oldDownload;
 balancePanel='destinies';renderBalance();check($('results').textContent.includes('Normal mastery pick')&&$('results').textContent.includes('Extra reward'),'normal and reward destiny split');
 balancePanel='modes';renderBalance();check($('results').textContent.includes('Gain 2 gems')&&$('results').textContent.includes('20'),'mode event counts visible');
 balancePanel='overview';renderBalance();check(document.documentElement.scrollWidth<=window.innerWidth,'balance view fits viewport');tab('heroes');check(!document.querySelector('.filters').hidden&&!$('gridView').disabled,'normal view restores controls after balance');
 const marker=document.createElement('div');marker.id='browser-test-result';marker.textContent='PASS '+checks+' checks';document.body.append(marker);
} catch(error){const marker=document.createElement('pre');marker.id='browser-test-result';marker.textContent='FAIL '+error.stack;document.body.append(marker)}
</script>'''

class StatisticsBrowserTests(unittest.TestCase):
    @unittest.skipUnless(CHROME.is_file(), 'Chromium is not installed')
    def test_gallery_sources_images_and_unknown_outcomes(self):
        html=(HERE/'statistics_dashboard.html').read_text()
        html=html.replace('<script>', '<script>window.fetch=()=>new Promise(()=>{});</script><script>', 1).replace('</body>',HARNESS+'</body>')
        with tempfile.TemporaryDirectory(prefix='shards-statistics-ui-') as temporary:
            root=Path(temporary);fixture=root/'fixture.html';fixture.write_text(html)
            for width in (1440,430):
                with self.subTest(width=width):
                    result=subprocess.run([str(CHROME),'--no-sandbox','--disable-gpu','--disable-background-networking','--disable-dev-shm-usage','--run-all-compositor-stages-before-draw','--virtual-time-budget=250','--hide-scrollbars',f'--window-size={width},1150','--user-data-dir='+str(root/f'profile-{width}'),'--dump-dom',fixture.as_uri()],capture_output=True,text=True,timeout=30)
                    self.assertEqual(result.returncode,0,result.stderr[-2000:])
                    self.assertTrue('<div id="browser-test-result">PASS ' in result.stdout,result.stdout[-1500:])

if __name__=='__main__':unittest.main()
