<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Assets/Scripts/Core/**/*.cs" LinkBase="Core" />
    <Compile Include="../../../Assets/Scripts/Shards/Engine/**/*.cs" LinkBase="Engine" />
    <Compile Include="../../../Assets/Scripts/Shards/Content/**/*.cs" LinkBase="Content" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
