using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Newtonsoft.Json.Linq;
using Pascension.Core;
using Shards.Bots;
using Shards.Content;
using Shards.Engine;

namespace SoiSim
{
    /// <summary>emit-net: embeds a trained weights.bin/.json as the generated
    /// ShardsNetWeights.g.cs (Base64 f16 + header consts). netfixture: writes 64
    /// deterministic encoded states for train.py to stamp expected outputs — the
    /// committed parity fixture that pins C# forward == PyTorch.</summary>
    public static class EmitNetCommand
    {
        public static int RunEmit(Cli cli)
        {
            string binPath = cli.GetStr("--bin", null) ?? throw new CliError("--bin required");
            string jsonPath = cli.GetStr("--json", null) ?? throw new CliError("--json required");
            string outPath = cli.GetStr("--out", Path.Combine(SimConfig.FindRepoRoot(),
                "Assets", "Scripts", "Shards", "Bots", "Neural", "ShardsNetWeights.g.cs"));
            cli.RejectUnknown();

            var header = JObject.Parse(File.ReadAllText(jsonPath));
            byte[] blob = File.ReadAllBytes(binPath);
            int schema = header.Value<int>("schemaVersion");
            int features = header.Value<int>("featureCount");
            var layers = header["layers"].ToObject<int[]>();
            string sha = header.Value<string>("sha256");
            int generation = header.Value<int>("generation");

            // Sanity: the blob must load before we embed it.
            _ = new ShardsNeuralEval(blob, layers, schema, sha);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// SoI value-net weights, embedded as Base64 f16 blobs so the SAME bytes ship");
            sb.AppendLine("// headless, in the editor and in IL2CPP builds (no file IO, no StreamingAssets).");
            sb.AppendLine("// Regenerate with:  soisim emit-net --bin <weights.bin> --json <weights.json>");
            sb.AppendLine($"// Generation {generation} · valAcc {header.Value<double?>("valAcc")} · " +
                          $"{header.Value<long?>("positions"):N0} positions · {DateTime.Now:yyyy-MM-dd}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("namespace Shards.Bots");
            sb.AppendLine("{");
            sb.AppendLine("    public static class ShardsNetWeights");
            sb.AppendLine("    {");
            sb.AppendLine("        public static bool Available => true;");
            sb.AppendLine();
            sb.AppendLine($"        public static int SchemaVersion => {schema};");
            sb.AppendLine($"        public static int FeatureCount => {features};");
            sb.AppendLine($"        public static int[] Layers => new[] {{ {string.Join(", ", layers)} }};");
            sb.AppendLine($"        public static string Sha256 => \"{sha}\";");
            sb.AppendLine($"        public static int Generation => {generation};");
            sb.AppendLine();
            sb.AppendLine("        public static string CurrentBlob => string.Concat(");
            string base64 = Convert.ToBase64String(blob);
            const int chunk = 60000;
            for (int i = 0; i < base64.Length; i += chunk)
            {
                string piece = base64.Substring(i, Math.Min(chunk, base64.Length - i));
                sb.AppendLine($"            \"{piece}\"{(i + chunk < base64.Length ? "," : ");")}");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(false));
            Console.WriteLine($"emit-net: generation {generation}, {blob.Length:N0} bytes -> {outPath}");
            return 0;
        }

        public static int RunFixture(Cli cli)
        {
            string outPath = cli.GetStr("--out", Path.Combine(SimConfig.FindRepoRoot(),
                "Tools", "ShardsData", "neural", "fixtures.soip"));
            int count = cli.GetInt("--count", 64);
            cli.RejectUnknown();

            ShardsCardDatabase.Clear();
            ShardsContentRegistry.EnsureRegistered();
            var chars = ShardsContentRegistry.CharactersFor(SimConfig.AllDlc);
            var model = new ShardsValueModel();
            var features = new float[ShardsStateEncoder.FeatureCount];

            using var writer = new PositionWriter(outPath);
            ulong seed = 5000;
            while (writer.Written < count)
            {
                seed++;
                var specs = new List<PlayerSpec>
                {
                    new() { Name = "F0", CharacterId = chars[(int)(seed % (ulong)chars.Count)] },
                    new() { Name = "F1", CharacterId = chars[(int)((seed + 2) % (ulong)chars.Count)] }
                };
                var adapter = new ShardsEngineAdapter(
                    ShardsContentRegistry.StandardConfig(seed, specs, SimConfig.AllDlc));
                var bots = new IBotAgent[]
                {
                    new ShardsGreedyEvalBot(seed * 100, adapter.Inner, model),
                    new ShardsGreedyEvalBot(seed * 100 + 1, adapter.Inner, model)
                };
                // Sample the position after 40 accepted submits (mid-game variety).
                int guard = 0;
                while (!adapter.GameOver && guard++ < 40)
                {
                    var pending = adapter.PendingInput;
                    var action = bots[pending.PlayerIndex].Choose(pending, null)
                                 ?? adapter.DefaultActionFor(pending);
                    if (!adapter.Submit(action).Accepted)
                        adapter.Submit(adapter.DefaultActionFor(adapter.PendingInput));
                }
                if (adapter.GameOver || adapter.PendingInput?.Kind != Pascension.Engine.Core.PendingInputKind.Priority)
                    continue;
                int viewer = adapter.PendingInput.PlayerIndex;
                ShardsStateEncoder.Encode(adapter.Inner.State, viewer, features);
                writer.Write(features, z: 0, q: -1, seed, (ushort)guard, (byte)viewer, flags: 2);
            }
            Console.WriteLine($"netfixture: {count} encoded states -> {outPath}");
            return 0;
        }
    }
}
