"""Build a standalone, offline balance review of the stopped statistics cohort.

Run after the hero, pacing, card and opening analysis scripts. No model is loaded
and no game is played. The HTML also works when opened directly from disk.
"""
import argparse
import html
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--analysis-dir', type=Path, required=True)
    parser.add_argument('--output-dir', type=Path, required=True)
    args = parser.parse_args()
    data = {name: json.loads((args.analysis_dir / filename).read_text()) for name, filename in {
        'heroes': 'hero_analysis.json', 'pacing': 'pacing_results.json',
        'cards': 'cards_analysis.json', 'card_sensitivity': 'cards_sensitivity.json',
        'openings': 'openings_analysis.json', 'opening_sensitivity': 'openings_sensitivity.json',
        'conscription': 'pacing_conscription.json',
    }.items()}
    assert all(data[key]['games'] == 3780 for key in ('heroes', 'pacing', 'cards', 'openings'))
    assert not data['openings']['audit_issues']
    data['report'] = {'date': '2026-10-08', 'games': 3780, 'rules_changed': False,
                      'new_simulations': False, 'title': 'Shards balance review'}
    names = {'decima': 'Decima', 'tetra': 'Tetra', 'volos': 'Volos', 'kosynwu': 'Ko Syn Wu', 'rez': 'Rez'}
    hero_order = sorted(names, key=lambda key: -data['heroes']['heroes'][key]['win_rate'])
    pct = lambda value: f'{value * 100:.1f}%'
    h = html.escape
    hero_rows = []
    for key in hero_order:
        row = data['heroes']['heroes'][key]
        hero_rows.append(f'<tr><th>{names[key]}</th><td>{row["wins"]:,} / {row["n"]:,}</td>'
                         f'<td><strong>{pct(row["win_rate"])}</strong></td>'
                         f'<td>{pct(row["ci95"][0])}–{pct(row["ci95"][1])}</td>'
                         f'<td>{pct(row["mastery_reached"]["10"]/row["n"])}</td>'
                         f'<td>{row["mastery_round_means_reachers_only"]["10"]:.2f}</td>'
                         f'<td>{pct(row["wins_by_victory"].get("mastery",0)/row["wins"])}</td></tr>')
    matchup = '<thead><tr><th>Row hero wins against →</th>' + ''.join(f'<th>{names[k]}</th>' for k in hero_order) + '</tr></thead><tbody>'
    for key in hero_order:
        matchup += f'<tr><th>{names[key]}</th>'
        for opponent in hero_order:
            if key == opponent:
                matchup += '<td class="muted">—</td>'
            else:
                row = data['heroes']['heroes'][key]['opponents'][opponent]
                cls = 'up' if row['win_rate'] >= .55 else 'down' if row['win_rate'] <= .45 else ''
                matchup += f'<td class="{cls}" title="{row["wins"]}/{row["n"]}; 95% CI {pct(row["ci95"][0])}–{pct(row["ci95"][1])}">{pct(row["win_rate"])}</td>'
        matchup += '</tr>'
    matchup += '</tbody>'
    relic_rows = []
    for key, row in sorted(data['heroes']['relics'].items(), key=lambda kv: (hero_order.index(kv[1]['hero']), -kv[1]['n'])):
        single = row['only_this_relic_acquired']
        relic_rows.append(f'<tr><td>{names[row["hero"]]}</td><th><details><summary>{h(row["name"])}</summary><p class="rules">{h(row["rules_text"])}</p></details></th>'
                          f'<td>{row["n"]}</td><td>{pct(row["win_rate"])}</td><td>{pct(row["any_additional_relic_acquired"]/row["n"])}</td>'
                          f'<td>{single["wins"]}/{single["n"]} · {pct(single["win_rate"]) if single["n"] else "—"}</td>'
                          f'<td>{row["m10_round_mean"]:.2f}</td></tr>')
    hist = data['pacing']['round_histogram']
    bars = []
    for round_num, count in sorted(hist.items(), key=lambda kv:int(kv[0])):
        bars.append(f'<div class="bar"><span>{round_num}</span><div style="width:{count/max(hist.values())*100:.2f}%"></div><small>{count:,}</small></div>')
    milestone_rows = []
    for milestone in ('5', '10', '20', '30'):
        row = data['pacing']['thresholds'][milestone]
        raw = row['both_different_round']['leader_win']
        adj = row.get('both_earlier_standardized')
        adjusted = f'{pct(adj["rate"])} ({pct(adj["ci95"][0])}–{pct(adj["ci95"][1])})' if adj and adj.get('rate') is not None else 'Too sparse'
        milestone_rows.append(f'<tr><th>Mastery {milestone}</th><td>{raw["n"]:,}</td><td>{pct(raw["rate"])}</td><td>{pct(raw["ci95"][0])}–{pct(raw["ci95"][1])}</td><td>{adjusted}</td></tr>')
    opening_rows = []
    for key in ('giga_source_adept', 'j_chord_duel', 'shard_abstractor'):
        row = next(r for r in data['openings']['opening_market'] if r['id'] == key)
        adj = row['adjustment']
        opening_rows.append(f'<tr><th>{h(row["name"])}</th><td>{row["offered"]["games"]}</td><td>{pct(row["offered"]["seat0_win_rate"])}</td>'
                            f'<td>{pct(row["absent"]["seat0_win_rate"])}</td><td>+{adj["adjusted_difference"]*100:.1f} pp ({adj["ci95"][0]*100:.1f}–{adj["ci95"][1]*100:.1f})</td>'
                            f'<td>{row["round1_acquisition_when_offered"][0]}/{row["offered"]["games"]}</td><td>{adj["q"]:.4f}</td></tr>')
    body = TEMPLATE.replace('@@HERO_ROWS@@', ''.join(hero_rows)).replace('@@MATCHUP@@', matchup)
    body = body.replace('@@RELIC_ROWS@@', ''.join(relic_rows)).replace('@@BARS@@', ''.join(bars))
    body = body.replace('@@MILESTONES@@', ''.join(milestone_rows)).replace('@@OPENING_ROWS@@', ''.join(opening_rows))
    encoded = json.dumps(data, ensure_ascii=False, allow_nan=False).replace('<', '\\u003c').replace('&', '\\u0026')
    body = body.replace('@@DATA@@', encoded)
    assert '@@' not in body
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / 'balance-review.html').write_text(body)
    (args.output_dir / 'balance-review-data.json').write_text(json.dumps(data, ensure_ascii=False, indent=2, allow_nan=False) + '\n')
    print(json.dumps({'html': str(args.output_dir / 'balance-review.html'), 'games': 3780, 'bytes': len(body.encode())}))


TEMPLATE = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Shards · Balance review · 3,780 games</title>
<style>
:root{color-scheme:dark;--bg:#101722;--panel:#172230;--ink:#eef3fb;--dim:#b4c3d5;--line:#334357;--accent:#91caff;--green:#8ce0be;--amber:#ffcd8a}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:36px 24px 100px}a{color:var(--accent)}h1{font-size:clamp(30px,4vw,48px);line-height:1.1;margin:15px 0}h2{font-size:27px;margin:0 0 16px}h3{font-size:20px}p{max-width:1000px}section{scroll-margin-top:20px;margin-top:34px;padding:27px;background:var(--panel);border:1px solid var(--line);border-radius:14px}.eyebrow,.muted,small{color:var(--dim)}.eyebrow{letter-spacing:.12em;font-size:12px;text-transform:uppercase}.lede{font-size:19px}.nav{display:flex;gap:10px 20px;flex-wrap:wrap;margin:24px 0}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.metric{background:var(--panel);border:1px solid var(--line);padding:18px;border-radius:10px}.metric b{display:block;font-size:30px}.metric span{color:var(--dim);font-size:14px}.callout{padding:16px 20px;border-left:4px solid var(--accent);background:#102033;margin:20px 0}.caution{border-color:var(--amber)}.table-scroll{overflow:auto}table{width:100%;border-collapse:collapse;margin:16px 0;font-variant-numeric:tabular-nums}th,td{padding:11px 13px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}thead th{font-size:13px;color:var(--dim);white-space:nowrap}tbody th{font-weight:600}.up{color:var(--green)}.down{color:var(--amber)}.rules{font-weight:400;white-space:pre-line;min-width:220px;font-size:14px;color:var(--dim)}summary{cursor:pointer}details>summary:hover{color:var(--accent)}.two{display:grid;grid-template-columns:1fr 1fr;gap:24px}.bar{display:grid;grid-template-columns:30px 1fr 45px;align-items:center;gap:12px;height:25px;font-size:13px}.bar div{background:var(--accent);height:13px;border-radius:3px}.bar small{text-align:right}.controls{display:flex;flex-wrap:wrap;gap:15px;align-items:end;margin:20px 0}label{font-size:13px;color:var(--dim)}input,select,button{display:block;padding:9px 12px;background:var(--bg);color:var(--ink);border:1px solid #61758e;border-radius:6px;font:inherit}button{cursor:pointer}button:hover{border-color:var(--accent)}input[type=number]{width:100px}ul,ol{padding-left:24px}li{margin:8px 0}.proposal{border-left:3px solid var(--line);padding:0 0 0 20px;margin:28px 0}.proposal:first-of-type{border-color:var(--green)}.tag{display:inline-block;color:var(--green);font-size:12px;border:1px solid #3b665c;padding:2px 8px;border-radius:20px}code{font-size:13px;overflow-wrap:anywhere}footer{margin-top:30px;color:var(--dim);font-size:13px}@media(max-width:750px){main{padding:20px 12px}section{padding:18px}.two{grid-template-columns:1fr}.metrics{grid-template-columns:1fr 1fr}th,td{padding:9px}h2{font-size:23px}}@media print{body{background:white;color:black}section,.metric{background:white;border-color:#bbb;break-inside:avoid}a{color:#146}nav,.controls{display:none}table{font-size:11px}.table-scroll{overflow:visible}.muted,small,thead th{color:#444}}
</style></head><body><main>
<div class="eyebrow">Shards of Infinity · Duel · 8 October 2026</div>
<h1>Balance evidence &amp; tuning plan</h1>
<p class="lede">A review of all <strong>3,780 completed statistics games</strong>, with Nyou Haïai and search on both sides. The clearest candidates are Giga's early mastery engine, Tetra's Multitask Brain, Volos's Panconscious Crown, and the free actions from Deadly Recruits.</p>
<p class="muted">Analysis only. No new games, training or balance changes. Each ordered pairing of different heroes has exactly 189 games; mirrors were not tested. Results describe this policy's play, and cannot fully separate rule balance from the AI's strategic preferences.</p>
<div class="callout"><a href="http://localhost:8767/balance-proposals"><strong>Review the complete proposed patch →</strong></a><br>All linked tunings, alternatives and exploratory ideas, with a saved review box for each suggestion.</div>
<nav class="nav"><a href="#heroes">Heroes</a><a href="#relics">Relics</a><a href="#pacing">Mastery & pacing</a><a href="#openings">Opening advantage</a><a href="#cards">Explore cards</a><a href="#destinies">Destinies & synergy</a><a href="#tunings">Tuning proposals</a><a href="#methods">Evidence & limits</a><a href="http://localhost:8767/statistics">Statistics panel ↗</a><a href="http://localhost:8767/games">All decklists ↗</a></nav>
<div class="metrics"><div class="metric"><b>9.98</b><span>Average rounds · median 10</span></div><div class="metric"><b>51.7%</b><span>First-player wins</span></div><div class="metric"><b>68.9%</b><span>Earlier M10 player wins¹</span></div><div class="metric"><b>70.1%</b><span>First-player wins with Giga offered</span></div></div>
<small>¹ Both players reached M10 in different rounds. This is an association, not the isolated benefit of a relic.</small>

<section id="heroes"><h2>1. Tetra leads; Volos struggles to convert</h2>
<div class="table-scroll"><table><thead><tr><th>Hero</th><th>Wins / games</th><th>Win rate</th><th>95% interval</th><th>Reaches M10</th><th>Mean M10 round²</th><th>Mastery share of wins</th></tr></thead><tbody>@@HERO_ROWS@@</tbody></table></div>
<small>² Among players who reached M10, not everyone. Threshold means are affected by survival.</small>
<p><strong>Tetra beats every other hero</strong>, although the Decima matchup is close. She reaches M5 later than the others, so earlier hero unlock is not the explanation. Her hero ability draws two cards for three gems; the additional draw engine in Multitask Brain pairs that cycling with direct power. Ordinary damage accounts for <strong>77.7% of Tetra's wins</strong>.</p>
<p><strong>Volos reaches M10 in 91.5% of games</strong>, more often than any other hero, and at the earliest conditional average. More starting mastery would address a bottleneck the data does not show. His Crown route reaches M20 often but loses before completing the mastery race.</p>
<p><strong>Rez is near even at 49.3%</strong>. He uses his hero ability 6.39 times per game and rerolls 5.21 times, about twice the other heroes. Mastery supplies 428 of his 745 wins. The older training's low Rez score is not reproduced here. Ko's thinning is also active: 6.08 starter banishes per game, versus 1.54–2.04 for the others. Decima's zero activation counter is expected: Recruiting is passive.</p>
<h3>Matchups, pooled across both starting seats</h3><p class="muted">378 games per matchup. Hover over a cell for counts and uncertainty; the diagonal was not sampled.</p>
<div class="table-scroll"><table>@@MATCHUP@@</table></div>
<div class="callout caution"><strong>Hero versus relic cannot be isolated from these games.</strong> The AI chooses relics to fit an evolving deck. Games with no relic played end sooner and select different strategies; those subsets are not valid estimates of the hero power alone. A forced-choice experiment at comparable game states is needed for that decomposition.</div></section>

<section id="relics"><h2>2. Relic rankings contain a large selection trap</h2>
<p><strong>859 player records acquired more than one distinct relic.</strong> Another 101 acquired a relic without making the normal M10 selection. Ingeminex Corruption can grant a relic straight to hand, outside that normal choice. The panel's selected-relic win rate therefore mixes standalone choices with reward-enriched decks.</p>
<p>Terminal Crescents has an additional relic in <strong>67 of 72</strong> selections; World Piercer in <strong>22 of 28</strong>; Unknown God in <strong>56 of 85</strong>. Their attractive raw results are insufficient grounds for a nerf. “Only this relic acquired” removes that particular contamination, but still conditions on later rewards and survival.</p>
<div class="table-scroll"><table><thead><tr><th>Hero</th><th>Normal relic choice · expand for rules</th><th>Games</th><th>Win rate</th><th>Also acquired another</th><th>Only this relic acquired</th><th>Mean M10 round</th></tr></thead><tbody>@@RELIC_ROWS@@</tbody></table></div>
<div class="two"><div><h3>Multitask Brain: likely Tetra pressure</h3><p>Chosen in <strong>90.1%</strong> of Tetra's normal relic selections; <strong>734/1,190 wins = 61.7%</strong>. Its measured-timing-adjusted association remains 61.4%. It grants one draw and two power per distinct faction played, with four power per faction at M20. A normal play counts Brain's own Order faction; Prism supplies all five factions. The count is sampled once before drawing, so the maximum is <strong>10 power + 5 draws</strong>, or <strong>20 power + 5 draws at M20</strong>. The hypothesis is excessive damage attached to strong cycling, not simply early mastery.</p></div><div><h3>Crown: a weak mastery route</h3><p><strong>95/299 wins = 31.8%</strong>, versus Talons' <strong>485/998 = 48.6%</strong>. Crown is selected with earlier M10 than Talons, and the gap persists after measured timing adjustment (30.5% vs 48.3%). Crown players reach M20 in 59.5% of games but average 10.96 rounds, versus Talons' 35.1% and 10.30 rounds. Adding more healing may prolong the losing route; cycling is the more plausible knob.</p></div></div>
<p><strong>Crown + Talons is an important exception.</strong> Volos acquired both relics in 75 games and won <strong>60/75 (80.0%)</strong>; both were played sometime in 70 games, with <strong>60/70 wins (85.7%)</strong>. These selected, reward-enriched decks do not establish a causal combo effect or same-turn use. The interaction is real, however: playing Talons before Crown supplies another Undergrowth play for Unify. Crown gains two mastery before checking M20, so it can cross 18 → 20 and convert its five healing plus the Unify fifty into <strong>55 power even at full health</strong>. Improving Crown's cycling could strengthen this rare burst route as well as its weak standalone route.</p>
<p><strong>Praetorian-03 is not a supported nerf.</strong> Its raw 56.2% versus Praetorian-01's 48.7% disappears after adjusting measured selection/mastery timing: 52.7% versus 53.4%. This is a concrete example of why raw relic ranks can mislead.</p>
<details><summary>Doom Gate: does it feed the opponent too much?</summary><p>It adds 35 monsters, including seven Corruptions, and shuffles the center deck. Both players can benefit, but in 272 Ko games where it was played, Ko defeated 2.36 monsters per game versus the opponent's 1.11; 128 Ko players acquired multiple relics versus 55 opponents. Ko won 59.2% in that selected group. Rewards first acquired in a strictly later round than the first Doom Gate play occurred in 59 Ko cases versus 40 opponents; same-round order is unknown. There is no evidence the flood systematically benefits the opponent more. Increasing monster count is not justified.</p></details></section>

<section id="pacing"><h2>3. Mastery 10 is a strong lead indicator</h2>
<div class="table-scroll"><table><thead><tr><th>Milestone</th><th>Both reached in different rounds</th><th>Earlier player wins</th><th>95% interval</th><th>Adjusted for matchup & seat</th></tr></thead><tbody>@@MILESTONES@@</tbody></table></div>
<p><strong>M10 lead of one round: 62.2% wins; two rounds: 71.7%; three or more: 78.9%.</strong> In games still alive after round 6, when exactly one player had already reached M10, that player won <strong>1,126/1,491 = 75.5%</strong>. The association remains strong before terminal states, although a good opening deck and economy can cause both early mastery and victory.</p>
<p>M10 is not instant relic output: normal recruitment puts the relic in <strong>discard</strong>. 19.2% of selected relics were never played before the end. Among those played, only 14.7% were first played in the selection round; another 38.8% arrived the next round. A lead can therefore mean an entire shuffle cycle of extra access. Some passive relic effects work from discard, so “never played” is not “useless.”</p>
<div class="callout caution">The 16 games where both players reached M30 are a survival trap: they exclude the many games immediately ended by the first Infinity Shard. Their low earlier-player win rate does <strong>not</strong> mean reaching M30 is harmful. Likewise, same-round threshold ties cannot be ordered from these logs.</div>
<div class="two"><div><h3>The pace already centers on ten rounds</h3><p>Mean <strong>9.98</strong>, median <strong>10</strong>; middle 80%: <strong>8–12</strong> rounds. 18.0% end by round 8; 65.3% in rounds 9–11; 16.7% in round 12 or later.</p><p>Victory routes: <strong>62.4% ordinary damage</strong>, <strong>32.3% mastery/Infinity</strong>, 3.7% Comet, 1.6% other health loss. Faster games alone would not establish a healthier balance.</p><p>First-player wins are <strong>51.72% [50.13–53.31]</strong>. The second player already starts with +1 mastery and +1 first-turn gem, and reaches M5 earlier in 81.8% of distinguishable M5 races. Target opening outliers before changing global compensation.</p></div><div><h3>Final round distribution</h3>@@BARS@@<small>Round is not turns per player. At least 408 games have extra turns.</small></div></div></section>

<section id="openings"><h2>4. Giga creates the clearest opening advantage</h2>
<p>To check whether “good players bought it” explains the acquisition results, I reconstructed every <strong>initial market and both opening hands</strong> using the exact frozen host and original seeds. No games were played. All 7,560 assigned heroes matched. The opening market exists before the first decision, making it a stronger opportunity check than final deck ownership.</p>
<div class="table-scroll"><table><thead><tr><th>Initially offered</th><th>Games</th><th>First-seat wins if offered</th><th>If absent</th><th>Adjusted difference · 95% CI</th><th>First-seat round-1 acquisitions</th><th>Corrected q</th></tr></thead><tbody>@@OPENING_ROWS@@</tbody></table></div>
<p class="muted">Adjustment: ordered hero matchup and both hands' base buying power. Percentage points, not relative percentages. Corrected q accounts for scanning 90 card offers. This measures the first player's advantage from shared initial availability, not the overall causal value of a card or a first-turn fast-play.</p>
<p>Giga was taken by the first player in <strong>all 117 initial offers</strong>. That player reached M10 by round 6 in <strong>48.7%</strong> of games versus <strong>23.4%</strong> when Giga was absent, and M20 by round 8 in <strong>37.6%</strong> versus <strong>9.7%</strong>. Mastery wins rose from 16.8% to 38.5% of those first-seat games. The advantage has the same sign in both seed halves (71.4% vs 51.6%; 68.1% vs 50.7%). These are mechanism clues from the same cohort, not independent replication.</p>
<p>A sensitivity model accounting for all 90 card definitions in the six market slots gives Giga <strong>+18.25 percentage points [9.44, 27.06]</strong> versus the observed average market card, corrected q = .0044. This uses card counts and a relative replacement contrast; it avoids interpreting a presence-only model as freely adding a seventh card. It remains an association from the same games.</p>
<p><strong>Giga costs two, has four defense, draws when played, and exhausts for three mastery with Dominion.</strong> It does not draw on a normal purchase or direct-to-play recruitment. Its repeatable mastery acceleration is the first tuning target. Early J-Chord and Shard Abstractor also deserve attention, but a simultaneous broad nerf would obscure which change works.</p>
<p>Example initial-Giga games: <a href="http://localhost:8767/games#game=6f105e192973800c">#13 · first-seat win</a>, <a href="http://localhost:8767/games#game=6f105e192973803f">#64 · first-seat win</a>, <a href="http://localhost:8767/games#game=6f105e192973804b">#76 · first-seat loss</a>. These illustrate recorded decks; they are not selected as proof.</p>
<h3>Can a first-turn fast-play swing the game?</h3>
<p>The exact answer is <strong>not recoverable</strong> for all games. The trace stores the first acquisition round and lifetime fast-play counts separately; it does not pair every acquisition's round with its mode. Hand-play timestamps exclude immediate fast-plays. Treating every round-1 acquisition of a mercenary as a fast-play would be wrong.</p>
<p>Where every recorded acquisition of a card was a fast-play, a first-round acquisition is guaranteed to be one: Shadow Apostle <strong>123/245 wins (50.2%)</strong>, Umbral Scourge <strong>27/68 (39.7%)</strong>, Cinder Scars <strong>28/53 (52.8%)</strong>, Shard Abstractor <strong>17/32 (53.1%)</strong>. None supplies a supported positive adjusted outlier. These subsets condition on later acquisition modes, so they cannot prove fast-playing is neutral or bad. Between <strong>465 and 860 player records</strong> had some first-round fast-play, based on conservative bounds.</p></section>

<section id="cards"><h2>5. Explore every measured card</h2>
<p>Use early acquisition views for balance hypotheses. Lifetime ownership and final collections favor cards bought on winning turns. A Comet owner win rate of 78.7% is not evidence that Comet itself adds 28.7 points.</p>
<div class="controls"><label>View<select id="card-view"><option value="by_second_round">Acquired by round 2</option><option value="first_round">Acquired in round 1</option><option value="first_round_fast_guaranteed">Guaranteed round-1 fast-play subset</option><option value="ever_acquired">Ever acquired · descriptive</option><option value="final_collection">In final collection · descriptive</option><option value="destinies">Normal destiny selections</option></select></label><label>Search<input id="card-search" placeholder="Card, faction or type"></label><label>Minimum sample<input id="card-min" type="number" min="1" value="30"></label><label>Order<select id="card-sort"><option value="effect">Adjusted association</option><option value="rate">Raw win rate</option><option value="sample">Sample size</option><option value="name">Name</option></select></label><button id="export-cards">Download this table</button></div>
<p id="card-count" class="muted" aria-live="polite"></p><div class="table-scroll"><table><thead><tr><th>Card · expand for current rules</th><th>Type / faction / cost</th><th>Wins / players</th><th>Raw win rate · 95% CI</th><th>Adjusted difference · 95% CI</th><th>Corrected q</th></tr></thead><tbody id="card-body"></tbody></table></div>
<small>Adjusted associations compare holders/choosers with other players within hero × opponent × seat, with game-clustered uncertainty. Destiny models also include selection round. These do not control all evolving deck state. Missing adjusted values indicate unsupported sample/model or a descriptive-only view. q &lt; .05 controls false discoveries within that exploratory family; it does not establish causality.</small></section>

<section id="destinies"><h2>6. Deadly Recruits stands out; specific synergies remain uncertain</h2>
<p><strong>Deadly Recruits: 485/752 wins = 64.5%</strong>. After matchup, seat and selection-round adjustment, the association is <strong>+11.0 percentage points [7.2, 14.8]</strong>; adding common first-round acquisitions leaves +10.7 points. Its raw win rate exceeds 50% for every hero, not just one combination.</p>
<p>Resolved choices were <strong>2,554 free fast-plays versus 489 free recruits</strong>—84% fast-play. A nerf aimed only at recruitment would miss its dominant use. There were 5,013 exhausts, but only 3,043 resolved choices: an activation count is not a successful-effect count.</p>
<p><strong>Unconditional Conscription</strong> and <strong>Soul Syphon</strong> are weaker choices: 42.0% and 44.5% raw wins, with adjusted associations of −7.9 and −7.1 points. Conscription requires two nonstarter allies costing at most two to produce four power. Soul Syphon currently heals seven after playing cards of at least three factions; that condition may make its healing unreliable, and healing cannot prevent an Infinity kill. Successful-trigger logging is needed before a redesign.</p>
<p>Conscription's initial availability is associated with first-seat wins falling from <strong>53.4% to 44.9%</strong>, adjusted −8.7 points. Its presence barely changes M5 priority. When the first seat chooses it, that player often selects after the opponent (135/210 cases) and wins only 34.3%; second-seat choosers win 49.5%. This is consistent with a weak fallback in the shared destiny row, but does not prove selection causes the loss.</p>
<h3>Synergy: plausible mechanics, limited identification</h3>
<p>Brain + Agony of Choice wins <strong>76/103 (73.8%)</strong>; Slipstream Shard + Deadly Recruits <strong>79/108 (73.1%)</strong>; Praetorian-03 + Deadly Recruits <strong>76/105 (72.4%)</strong>. These are selected combinations, often enabled by a strong opening or an extra relic.</p>
<p><strong>No hero-specific early-card interaction passed correction across 221 tests; no supported early-card pair passed across 119 tests; no hero × initial destiny offer passed across 150 tests.</strong> This does not establish that synergy is absent. It means this cohort cannot reliably distinguish particular synergy bonuses from main effects, choice bias and small samples. Giga's early win rate is at least 60% with every hero, but those per-hero samples are only 34–50.</p></section>

<section id="tunings"><h2>7. Proposed tuning sequence</h2>
<p>Each entry is a separate experiment, in this order. The numbers are starting hypotheses, not guaranteed fixes. Do not stack them before measuring their individual effect.</p>
<div class="proposal"><span class="tag">First proposal</span><h3>1 · Giga: Dominion mastery 3 → 2</h3><p><strong>Keep cost 2, defense 4 and Draw 1.</strong> Add a Duel-specific replacement so other formats retain their rules. This targets the repeatable mastery acceleration supported by both early acquisition and initial-offer evidence.</p><p>Why this knob: first-seat M20-by-round-8 rises nearly fourfold when Giga is initially available. All opening first-seat hands can already generate at least three gems, so raising price 2 → 3 would change competition with Focus and other buys, not remove access. It is an alternative experiment, not a second simultaneous nerf.</p><p>Watch initial-offer advantage, M10/M20 timing, mastery wins, game-length tails and effects on Rez. A reduction in Giga's skew without suppressing the general mastery route would support keeping it. The logs do not count successful Dominion triggers, so the exact marginal contribution remains unmeasured.</p></div>
<div class="proposal"><h3>2 · Deadly Recruits: activation costs 1 gem</h3><p>Preserve its fast-play/recruit choice and the existing cost limits. Free recurring actions are the suspected excess; the observed use is mostly fast-play. One gem is a meaningful test and could be too severe, so check whether it becomes a discarded choice, especially before M20.</p></div>
<div class="proposal"><h3>3 · Multitask Brain: pre-M20 power per faction 2 → 1</h3><p>Keep the draw per faction and initially retain the M20 tier. This reduces Tetra's damage conversion while preserving her cycling identity. Check her full matchup matrix and whether the AI switches relics. This is a substantial numerical nerf, not a demonstrated exact correction; test it separately from Giga and Deadly Recruits.</p></div>
<div class="proposal"><h3>4 · Panconscious Crown: add Draw 1</h3><p>Retain two mastery, five healing and the M20 Unify healing tier. The goal is to make its mastery route cycle reliably rather than extend an ineffective stall. Compare Crown against Talons in matched decision states and inspect long games/M30 conversion. <strong>Also track Crown + Talons separately:</strong> adding a draw may make its 55-power healing conversion more consistent. Record reward relics, same-turn play order and healing converted to power, rather than relying on final ownership. First verify whether better relic selection alone fixes Volos, because a policy error can mimic a weak relic.</p></div>
<div class="proposal"><h3>5 · Diagnose weak destinies before redesigning</h3><p>Log successful triggers for Conscription and Soul Syphon. If reliability is the issue, possible independent redesigns are Conscription: one cheap nonstarter ally → two power; Soul Syphon: two factions → five health. Each lowers the condition and the payout. Neither is ready to ship from these data alone.</p></div>
<details><summary>Lower-priority cards and optional new mechanic</summary><p>Furrowing Elemental's early 19/61 record (31.1%) suggests testing cost 5 → 4 only after examining its use; the sample is small, and a weak early purchase need not be a weak card. J-Chord, Shard Abstractor, Order Initiate and Shard Seer deserve a second pass after the first change. Avoid nerfing the entire early mastery engine simultaneously.</p><p>A new card is not needed to address the clearest signals. If reducing mastery snowball becomes a deliberate design goal, consider a modest defensive card with a bonus only while behind in mastery—for example one extra shield or one mastery. It needs a cost/output design and a separate test. An automatic relic-to-hand catch-up would be a much larger rule change and is not supported here.</p></details>
<h3>How to validate a candidate</h3><ol><li>Change one rule, verify its effect and keep all other rules fixed. Freeze the policy, search settings and a new seed list; play both starting seats for every matchup. Compare candidate and baseline in separate, paired-seed runs.</li><li>Track hero rates, relic choice and successful output, initial-offer advantage, victory routes and round distributions. A shared rules patch always gives one winner per self-play game, so an aggregate “patch win rate” is meaningless.</li><li>Use opportunity-based and fixed-round analyses. For relics, supplement ordinary play with forced-choice diagnostics from comparable legal decision states, stratified by extra-relic rewards. Do not force a card into an unsuitable deck and interpret that alone as strength.</li><li>Allow policy adaptation before making a final decision. A model trained on old effects can initially buy, discard or activate cards incorrectly after a patch. Check another policy or human review to avoid balancing only this AI's habits.</li><li>Predeclare the acceptable balance range and uncertainty before running the confirmatory batch. Repeatedly checking until a favorable result appears overstates confidence. No such experiments were run during this review.</li></ol>
<p><strong>Retain global M10/M30 thresholds, starting compensation, and Rez/Decima's hero powers for the first experiment.</strong> Targeted candidates have stronger evidence than sweeping pacing changes.</p></section>

<section id="methods"><h2>8. What was checked—and what the logs cannot tell us</h2>
<p>The trace and decklist export match exactly after excluding the display game number. There are 3,780 unique completed games, no draws or censored records, balanced ordered matchups, valid hero/relic identities, valid mastery-round ordering and consistent acquisition counts. The original 240 and optimized 3,540 games use the same frozen model/settings; their mean lengths are 9.946 and 9.983 rounds. The smaller subgroup is not evidence of a balance difference.</p>
<p>Raw proportions use Wilson 95% intervals. Opening-offer models use one row per game, ordered-matchup and opening-resource controls, and HC3 robust intervals. Player-level acquisition models cluster errors by game so two opposing outcomes are not treated as independent. Exploratory card families use Benjamini–Hochberg correction. Relic timing models standardize measured covariates but cannot remove unrecorded deck, health or choice bias.</p>
<p>Opening offers are shared and the market has six slots: availability shifts competitors' options and co-occurs with other cards. Joint opening-market sensitivity is included in the download, with its composition limitations; no coefficient should be read as a literal independent “add this card” intervention. All sensitivity checks reuse the discovery cohort.</p>
<details><summary>Telemetry limitations that materially affect balance conclusions</summary><ul><li>First mastery, acquisition and play timestamps have <strong>round</strong> granularity. Same-round order, extra-turn action sequences and later mastery losses cannot be reconstructed.</li><li>First acquisition round is not paired with purchase mode; lifetime fast-play counts pool paid and free effects. Exact first-turn fast-play attribution is missing.</li><li>Normal relic choice omits reward relics. Extra rewards must be read from acquisition maps. Final ownership and “no extra relic” restrictions depend on future events.</li><li>Healing counts actual HP restored, excluding at-cap healing that still becomes power through Talons or Nectar Alchemist. Shield totals count revealed hand values, not effective damage prevented, and omit passive shields.</li><li>Ordinary face-damage counters include overkill and exclude Infinity attacks; they do not isolate card sources or champion damage. Draw totals include setup and cleanup.</li><li>Exhausts and hero activations are attempts, not proof conditional effects succeeded. Successful Dominion/Unify/Conscription triggers and source-attributed outputs are missing.</li><li>No complete action log, live offer history or per-turn economy snapshots were saved. The initial-state reconstruction recovers the opening, not every later decision.</li><li>The game cohort contains distinct-hero matches only, one policy family and current custom Duel rules. Confidence intervals cover sampling uncertainty, not all strategic/model bias.</li></ul></details>
<h3>Minimum additional telemetry for the next test</h3><p>Record action and turn ordinals; threshold crossing order; acquisition round + mode + source; available card/relic/destiny choices; every relic's source and first effective use; successful conditional effects; actual damage prevented; healing converted to power; and source-attributed resource changes. Keep compact aggregates plus sampled full replays. Measure logging overhead before enabling it in high-throughput training.</p>
<div class="controls"><button id="download-data">Download all analysis tables (JSON)</button><button onclick="window.print()">Print / save as PDF</button></div>
<details><summary>Reproduction and provenance</summary><p>Scripts are in <code>Tools/BalanceReview/</code>: <code>hero_analysis.py</code>, <code>pacing_analysis.py</code>, <code>pacing_conscription.py</code>, <code>cards_analysis.py</code>, <code>cards_sensitivity.py</code>, <code>openings_analysis.py</code>, <code>openings_sensitivity.py</code>, and <code>build_report.py</code>. <code>OpeningsHost</code> loads the exact frozen host to reconstruct initial states only.</p><p>Input: <code>new-ai-search-statistics-10000-optimized/strategy-prefix.jsonl</code>, the frozen <code>card-catalog.json</code> and host manifest. Detailed tables and source hashes are embedded in this standalone HTML and included in the JSON download.</p><pre id="provenance"></pre></details></section>
<footer>Prepared from the stopped statistics cohort, 8 October 2026. Balance changes remain proposals.</footer>
</main><script id="report-data" type="application/json">@@DATA@@</script><script>
'use strict';
const D=JSON.parse(document.getElementById('report-data').textContent);
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=x=>Number.isFinite(x)?(100*x).toFixed(1)+'%':'—', ci=x=>x?.length===2?`${pct(x[0])}–${pct(x[1])}`:'—';
let current=[];
function refresh(){
 const key=$('card-view').value, query=$('card-search').value.toLowerCase().trim(), min=Math.max(1,Number($('card-min').value)||1);
 current=D.cards[key].filter(r=>r.n>=min && [r.name,r.id,r.faction,r.type].join(' ').toLowerCase().includes(query));
 const order=$('card-sort').value;
 current.sort((a,b)=>order==='name'?a.name.localeCompare(b.name):order==='sample'?b.n-a.n:order==='rate'?b.winrate-a.winrate:(b.adjusted?.delta_pp??-Infinity)-(a.adjusted?.delta_pp??-Infinity));
 $('card-count').textContent=`${current.length} cards shown · ${key==='first_round_fast_guaranteed'?'Guaranteed subset only; later acquisition modes influence inclusion.':'Player records, not independent games. Expand a name to inspect its frozen rules.'}`;
 $('card-body').innerHTML=current.map(r=>{const a=r.adjusted,c=D.cards.catalog[r.id]||{},v=a?`${a.delta_pp>=0?'+':''}${a.delta_pp.toFixed(1)} pp<br><small>${a.ci95_pp.map(x=>x.toFixed(1)).join(' to ')}</small>`:'—';return `<tr><th><details><summary>${esc(r.name)}</summary><p class="rules">${esc(c.rules_text||'')}</p><small>${esc(r.id)}${r.possible_first_round_fast_count!=null?'<br>Possible upper bound: '+r.possible_first_round_fast_count:''}</small></details></th><td>${esc(c.type||r.type)}<br><small>${esc(c.faction||r.faction)} · cost ${esc(c.cost??r.cost)}</small></td><td>${r.wins}/${r.n}</td><td>${pct(r.winrate)}<br><small>${ci(r.ci95)}</small></td><td>${v}</td><td>${a?.q_within_family==null?'—':a.q_within_family<.0001?'&lt;0.0001':a.q_within_family.toFixed(4)}</td></tr>`}).join('');
}
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
['card-view','card-search','card-min','card-sort'].forEach(id=>$(id).addEventListener('input',refresh));
$('export-cards').onclick=()=>{const rows=[['id','name','sample','wins','win_rate','ci_low','ci_high','adjusted_pp','adjusted_ci_low','adjusted_ci_high','q'],...current.map(r=>[r.id,r.name,r.n,r.wins,r.winrate,...r.ci95,r.adjusted?.delta_pp,...(r.adjusted?.ci95_pp||['','']),r.adjusted?.q_within_family])];download(rows.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n')+'\n','shards-'+$('card-view').value+'.csv','text/csv')};
$('download-data').onclick=()=>download(JSON.stringify(D,null,2),'shards-balance-review-3780.json','application/json');
$('provenance').textContent=JSON.stringify(D.openings.provenance,null,2);refresh();
</script></body></html>'''


if __name__ == '__main__':
    main()
