// <auto-generated>
// Tuned weight vectors for the SoI value model. Regenerate with:
//   dotnet run -c Release --project Tools/SoiSim -- tune …
// V6: sep-CMA-ES self-play, 300 gens × λ16 × 240 games, seed 27, vs-heuristic 77.2 % (2026-07-27).
// Keep superseded vectors — they anchor the tuner's reference pool.
// </auto-generated>
namespace Shards.Bots
{
    public static class ShardsEvalWeights
    {
        /// <summary>The vector new bots use by default.</summary>
        public static double[] Current => V7;

        /// <summary>V5 plus ONLY the contextual-thinning weight (index 49). Hand-derived
        /// 2026-07-27, NOT emitted by the tuner — re-running `tune` will overwrite the file
        /// and drop this, so re-derive it if that happens.
        ///
        /// Why not V6. The full re-tune scored +5 Elo [50.3-51.3] over 15,000 pairs — real
        /// but small — while walking `PlayDeferPotential` from +0.495 to **-0.027**. That
        /// inverts the Carnivorous Vine deferral: rather than holding a conditional card back
        /// while an enabler is still in hand, a negative weight rewards playing it early.
        /// That rule was a deliberate fix worth ~5 points of win rate (78% -> 83.2% vs
        /// heuristic) and is pinned by PlayOrdering_DefersCarnivorousVineBehindItsEnabler,
        /// which V6 fails.
        ///
        /// Trading a designed, separately-measured behaviour for +5 Elo of aggregate is a bad
        /// trade, and "the tuner said so" is not a reason to accept an inverted rule: 300
        /// generations against a noisy win-rate fitness can find a local optimum that pays for
        /// one regression with several small unrelated gains.
        ///
        /// So V7 keeps every V5 value and adds only what V5 could not have had — the thinning
        /// scale, at the 0.914 the tuner itself landed on. V6 is retained below as the tuner's
        /// own answer and as a reference-pool anchor.</summary>
        public static readonly double[] V7 =
        {
            0.536983, 0.176469, 5.959982, 0.440221, 3.220118, -0.010798,
            0.322995, 0.278057, 0.323761, 1.250558, 5.539153, -0.001969,
            0.339705, 0.417094, 2.357603, -0.086964, 3.186298, -0.025701,
            1.738311, 0.400921, 1.339304, -0.110615, 0.648379, -0.093292,
            0.02659, 0.141512, 21.493941, 13.863935, 20.157387, 8.014701,
            358.055401, 1012.585932, 794.739403, 3267.691985, 266.275255, -0.008028,
            -0.133808, 1.614512, 0.574872, 3.044361, 810.703464, 139.841914,
            0.494735, 18.206587, 0.619598, 149.520047, 0.195783, 0.127628,
            -0.30456, 0.914063
        };

        public static readonly double[] V1 =
        {
            1.0, 1.0, 3.0, 0.3, 1.6, 0.6,
            0.3, 0.5, 0.5, 2.0, 2.0, 0.3,
            0.2, 1.0, 0.5, 0.3, 2.5, 0.8,
            1.2, 2.0, 1.5, 0.5, 0.5, 0.6,
            0.02, 0.67, 100.0, 10.0, 50.0, 20.0,
            1500.0, 1400.0, 1300.0, 1250.0, 500.0, 0.0,
            1.0, 1.0, 1.0, 1.0, 2000.0, 1000.0
        };

        public static readonly double[] V2 =
        {
            0.734086, 1.016715, 2.290401, 0.492532, 2.792551, 0.827822,
            0.360378, 0.399673, 0.642539, 0.650462, 2.583782, 0.430524,
            0.31646, 0.435493, 0.942091, -0.090962, 3.997345, -0.034016,
            1.415657, 1.392904, 0.868005, -0.216006, 0.855533, 0.620287,
            0.043537, 0.109602, 89.517792, 14.018496, 52.11965, 15.101423,
            1931.77859, 2378.948752, 2252.083406, 2069.74773, 174.388917, -0.021253,
            0.304371, 2.108113, 0.657461, 1.544885, 3055.00641, 1510.946034
        };

        public static readonly double[] V3 =
        {
            0.734086, 1.016715, 2.290401, 0.492532, 2.792551, 0.827822,
            0.360378, 0.399673, 0.642539, 0.650462, 2.583782, 0.430524,
            0.31646, 0.435493, 0.942091, -0.090962, 3.997345, -0.034016,
            1.415657, 1.392904, 0.868005, -0.216006, 0.855533, 0.620287,
            0.043537, 0.109602, 89.517792, 14.018496, 52.11965, 15.101423,
            1931.77859, 2378.948752, 2252.083406, 2069.74773, 174.388917, -0.021253,
            0.304371, 2.108113, 0.657461, 1.544885, 3055.00641, 1510.946034,
            0.6
        };

        public static readonly double[] V4 =
        {
            0.620702, 0.831612, 2.249631, 0.601319, 2.378237, 0.559355,
            0.285059, 0.328169, 0.306433, 0.973373, 2.423609, 0.423246,
            0.357442, 0.372858, 1.489174, -0.115988, 1.730981, -0.028551,
            1.240035, 1.239874, 0.896669, -0.111129, 0.664139, 0.601224,
            0.044413, 0.118269, 95.797604, 12.496452, 68.047845, 10.082671,
            1823.861669, 3060.532567, 1250.672545, 2593.407193, 223.653412, -0.023303,
            0.222302, 2.662084, 0.396819, 1.573399, 2679.246307, 1117.534703,
            0.488981
        };

        public static readonly double[] V5 =
        {
            0.536983, 0.176469, 5.959982, 0.440221, 3.220118, -0.010798,
            0.322995, 0.278057, 0.323761, 1.250558, 5.539153, -0.001969,
            0.339705, 0.417094, 2.357603, -0.086964, 3.186298, -0.025701,
            1.738311, 0.400921, 1.339304, -0.110615, 0.648379, -0.093292,
            0.02659, 0.141512, 21.493941, 13.863935, 20.157387, 8.014701,
            358.055401, 1012.585932, 794.739403, 3267.691985, 266.275255, -0.008028,
            -0.133808, 1.614512, 0.574872, 3.044361, 810.703464, 139.841914,
            0.494735, 18.206587, 0.619598, 149.520047, 0.195783, 0.127628,
            -0.30456
        };

        public static readonly double[] V6 =
        {
            0.516979, 0.106189, 11.065763, 0.291961, 4.139761, 0.009512,
            0.280637, 0.287034, 0.282964, 1.843228, 9.02149, 0.032569,
            0.355035, 0.343946, 3.629097, -0.071316, 3.081583, -0.052558,
            2.040036, 0.300742, 1.421059, -0.096988, 0.343045, -0.105489,
            0.040332, 0.185037, 29.45671, 6.365507, 23.771707, 7.377161,
            230.280807, 1450.326514, 773.645831, 1881.47854, 235.838531, -0.016392,
            -0.054162, 2.182053, 0.14876, 2.692331, 853.751277, 11.609472,
            -0.027509, 23.47269, 0.817076, 17.169261, 0.117234, 0.069762,
            -0.110943, 0.914063
        };
    }
}
