// <auto-generated>
// Position-evaluator weights, FITTED to game outcomes. Regenerate with:
//   dotnet run -c Release --project Tools/SoiSim -- fit
// L1: logistic regression, holdout accuracy 64.3 %.
// L0: hand-set health+mastery baseline, kept as the control.
// </auto-generated>
namespace Shards.Bots
{
    public static class ShardsEvalLinearWeights
    {
        /// <summary>The vector the linear evaluator uses by default.</summary>
        public static double[] Current => L1;

        /// <summary>Hand-set control: the two terms measured to work.</summary>
        public static readonly double[] L0 =
        {
            2.0, 2.0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        };

        public static readonly double[] L1 =
        {
            1.472615, // health
            3.449513, // mastery
            1.043811, // gemsPerTurn
            5.849976, // powerPerTurn
            1.907635, // masteryPerTurn
            0.243223, // drawsPerTurn
            0.066005, // shieldPerTurn
            1.323055, // deckSize
            0.767685, // density
            2.849242, // champions
            -2.443162, // boardPower
            1.235536, // boardGems
            0.770583, // distinctFactions
            0.167621, // allegiance4
            -0.186856, // unifyLiveness
            3.449513, // toM30
            0.624260, // tempo
            -1.048718, // killRate
            -0.164856, // ascendRate
            5.871549, // killUrgency
            0.025065, // boardShare
            -0.836896, // cycleSpeed
        };
    }
}
