// <auto-generated>
// Tuned weight vectors for the SoI value model. Regenerate with:
//   dotnet run -c Release --project Tools/SoiSim -- tune …
// V2: sep-CMA-ES self-play, 300 gens × λ16 × 240 games, seed 7, vs-heuristic 79.9 % (2026-07-21).
// Keep superseded vectors — they anchor the tuner's reference pool.
// </auto-generated>
namespace Shards.Bots
{
    public static class ShardsEvalWeights
    {
        /// <summary>The vector new bots use by default.</summary>
        public static double[] Current => V2;

        public static readonly double[] V1 =
        {
            1.0, 1.0, 3.0, 0.3, 1.6, 0.6,
            0.3, 0.5, 0.5, 2.0, 2.0, 0.3,
            0.2, 1.0, 0.5, 0.3, 2.5, 0.8,
            1.2, 2.0, 1.5, 0.5, 0.5, 0.6,
            0.02, 0.67, 100.0, 10.0, 50.0, 20.0,
            1500.0, 1400.0, 1300.0, 1250.0, 500.0, 0.0,
            1.0, 1.0, 1.0, 1.0, 2000.0, 1000.0
        };

        public static readonly double[] V2 =
        {
            0.734086, 1.016715, 2.290401, 0.492532, 2.792551, 0.827822,
            0.360378, 0.399673, 0.642539, 0.650462, 2.583782, 0.430524,
            0.31646, 0.435493, 0.942091, -0.090962, 3.997345, -0.034016,
            1.415657, 1.392904, 0.868005, -0.216006, 0.855533, 0.620287,
            0.043537, 0.109602, 89.517792, 14.018496, 52.11965, 15.101423,
            1931.77859, 2378.948752, 2252.083406, 2069.74773, 174.388917, -0.021253,
            0.304371, 2.108113, 0.657461, 1.544885, 3055.00641, 1510.946034
        };
    }
}
