// GENERATED by generate-baseline.mjs — do not hand-edit. Regenerate after real card changes.
window.SOI_BASELINE = {
 "generatedAt": "2026-07-25",
 "source": "Tools/ShardsData/cards-table.md",
 "artDir": "../../Assets/Art/Shards/Cards/",
 "sets": [
  {
   "id": "base",
   "name": "Base game"
  },
  {
   "id": "relics_of_the_future",
   "name": "Relics of the Future"
  },
  {
   "id": "shadow_of_salvation",
   "name": "Shadow of Salvation"
  },
  {
   "id": "into_the_horizon",
   "name": "Into the Horizon"
  }
 ],
 "factions": [
  {
   "id": "Homodeus",
   "color": "#857542"
  },
  {
   "id": "Order",
   "color": "#3D6194"
  },
  {
   "id": "Undergrowth",
   "color": "#3D7A47"
  },
  {
   "id": "Wraethe",
   "color": "#6B4785"
  },
  {
   "id": "Aion",
   "color": "#9E5238"
  },
  {
   "id": "Monster",
   "color": "#8F2E2E"
  },
  {
   "id": "None",
   "color": "#52525C"
  }
 ],
 "types": [
  "Ally",
  "Champion",
  "Mercenary",
  "Relic",
  "Destiny",
  "Starter",
  "Monster",
  "Character"
 ],
 "keywords": [
  {
   "id": "exhaust",
   "name": "Exhaust",
   "faction": "",
   "kind": "text",
   "pattern": "\\bexhaust",
   "flags": "i",
   "meaning": "Tap this ready card to use its ability. It readies at your end phase."
  },
  {
   "id": "unify",
   "name": "Unify",
   "faction": "Undergrowth",
   "kind": "text",
   "pattern": "\\bUnify\\b",
   "flags": "",
   "meaning": "Active if you played or reveal another ally of this card's faction as you play this card."
  },
  {
   "id": "dominion",
   "name": "Dominion",
   "faction": "Order",
   "kind": "text",
   "pattern": "\\bDominion\\b",
   "flags": "",
   "meaning": "Active if you played or revealed a Homodeus, an Undergrowth and a Wraethe card this turn."
  },
  {
   "id": "inspire",
   "name": "Inspire",
   "faction": "Homodeus",
   "kind": "text",
   "pattern": "\\bInspire\\b",
   "flags": "",
   "meaning": "Active while you control a champion."
  },
  {
   "id": "echo",
   "name": "Echo",
   "faction": "Wraethe",
   "kind": "text",
   "pattern": "\\bEcho\\b",
   "flags": "",
   "meaning": "Grows with each card of this card's faction in your discard pile."
  },
  {
   "id": "warp",
   "name": "Warp",
   "faction": "Aion",
   "kind": "text",
   "pattern": "\\bWarp\\b",
   "flags": "",
   "meaning": "Fast-play a row ally costing up to the shown number for free (no number: any ally). It goes under the center deck at end of turn."
  },
  {
   "id": "mastery-threshold",
   "name": "Mastery threshold",
   "faction": "",
   "kind": "text",
   "pattern": "\\bM\\d+\\b",
   "flags": "",
   "meaning": "Needs that much Mastery when you play or exhaust this card."
  },
  {
   "id": "shield",
   "name": "Shield",
   "faction": "",
   "kind": "stat",
   "pattern": "",
   "flags": "",
   "meaning": "Reveal it from your hand when attacked to prevent that much damage. It stays in your hand. (Champion printed shields are inert in play.)"
  },
  {
   "id": "mercenary",
   "name": "Mercenary",
   "faction": "",
   "kind": "type",
   "pattern": "",
   "flags": "",
   "meaning": "Recruit it, or fast-play it for its cost: effect now, then under the center deck."
  },
  {
   "id": "ingeminex-attack",
   "name": "Attack (Ingeminex)",
   "faction": "Monster",
   "kind": "type",
   "pattern": "",
   "flags": "",
   "meaning": "Strikes every player at the end of the turn it appeared, unless it is defeated first. Not damage — shields don't prevent it."
  },
  {
   "id": "ingeminex-reward",
   "name": "Reward (Ingeminex)",
   "faction": "Monster",
   "kind": "type",
   "pattern": "",
   "flags": "",
   "meaning": "Deal it 10 total power to defeat it; only the player who defeats it claims the reward."
  }
 ],
 "cards": [
  {
   "id": "kiln_drone",
   "name": "Kiln Drone",
   "set": "base",
   "faction": "Homodeus",
   "types": [
    "Ally"
   ],
   "cost": 1,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 2 gems.\nInspire: gain 4 instead.",
   "art": "kiln_drone.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "korvus_legionnaire",
   "name": "Korvus Legionnaire",
   "set": "base",
   "faction": "Homodeus",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 3,
   "defense": null,
   "shield": 2,
   "text": "Shield 2.\nGain 2 power.\nReturn a champion from your discard pile to your hand.",
   "art": "korvus_legionnaire.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "mining_drones",
   "name": "Mining Drones",
   "set": "base",
   "faction": "Homodeus",
   "types": [
    "Ally"
   ],
   "cost": 2,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 1 gem and draw a card.",
   "art": "mining_drones.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "reactor_drone",
   "name": "Reactor Drone",
   "set": "base",
   "faction": "Homodeus",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 3 gems.",
   "art": "reactor_drone.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "furrowing_elemental",
   "name": "Furrowing Elemental",
   "set": "base",
   "faction": "Undergrowth",
   "types": [
    "Ally"
   ],
   "cost": 5,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 4 health and draw a card.\nIf you are at 50 health, gain 6 power.",
   "art": "furrowing_elemental.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "ojas_genesis_druid",
   "name": "Ojas, Genesis Druid",
   "set": "base",
   "faction": "Undergrowth",
   "types": [
    "Ally"
   ],
   "cost": 4,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Copy the effect of a non-champion card you played this turn.\nM20: copy it an additional time.",
   "art": "ojas_genesis_druid.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "shardwood_guardian",
   "name": "Shardwood Guardian",
   "set": "base",
   "faction": "Undergrowth",
   "types": [
    "Ally"
   ],
   "cost": 4,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 2 power and draw a card.\nUnify: gain 6 health.",
   "art": "shardwood_guardian.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "thorn_zealot",
   "name": "Thorn Zealot",
   "set": "base",
   "faction": "Undergrowth",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": 3,
   "text": "Shield 3.\nDraw a card.\nUnify: destroy an enemy champion.",
   "art": "thorn_zealot.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "undergrowth_aspirant",
   "name": "Undergrowth Aspirant",
   "set": "base",
   "faction": "Undergrowth",
   "types": [
    "Ally"
   ],
   "cost": 1,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 3 health.\nUnify: also gain 5 power.",
   "art": "undergrowth_aspirant.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "command_seer",
   "name": "Command Seer",
   "set": "base",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 4,
   "qty": 2,
   "defense": null,
   "shield": 5,
   "text": "Shield 5.\nGain 2 gems.",
   "art": "command_seer.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "cryptofist_monk",
   "name": "Cryptofist Monk",
   "set": "base",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 5,
   "qty": 2,
   "defense": null,
   "shield": 8,
   "text": "Shield 8.\nDraw a card.",
   "art": "cryptofist_monk.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "order_initiate",
   "name": "Order Initiate",
   "set": "base",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 1,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 2 gems.\nDominion: gain 2 mastery.",
   "art": "order_initiate.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "portal_monk",
   "name": "Portal Monk",
   "set": "base",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Recruit a card costing 6 or less for free.\nM15: it goes to your hand instead.",
   "art": "portal_monk.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "shadebound_sentry",
   "name": "Shadebound Sentry",
   "set": "base",
   "faction": "Wraethe",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 3 power.\nReturn a mercenary from your discard pile to your hand.",
   "art": "shadebound_sentry.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "wraethe_skirmisher",
   "name": "Wraethe Skirmisher",
   "set": "base",
   "faction": "Wraethe",
   "types": [
    "Ally"
   ],
   "cost": 1,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 2 power.\nEcho: gain 6 instead.",
   "art": "wraethe_skirmisher.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "drakonarius",
   "name": "Drakonarius",
   "set": "base",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 6,
   "qty": 1,
   "defense": 2,
   "shield": null,
   "text": "Can't be attacked while you control General Decurion.\nExhaust: gain 6 power.",
   "art": "drakonarius.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "evokatus",
   "name": "Evokatus",
   "set": "base",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 4,
   "qty": 2,
   "defense": 2,
   "shield": null,
   "text": "When played, draw a card.\nExhaust: gain 1 power per Homodeus champion you control.",
   "art": "evokatus.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "general_decurion",
   "name": "General Decurion",
   "set": "base",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 7,
   "qty": 1,
   "defense": 7,
   "shield": null,
   "text": "Exhaust: gain 3 gems.\nM20: also copy the effect of each Homodeus ally you play or played this turn.",
   "art": "general_decurion.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "numeri_drones",
   "name": "Numeri Drones",
   "set": "base",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 3,
   "qty": 2,
   "defense": 5,
   "shield": null,
   "text": "Exhaust: gain 1 gem; the next Homodeus champion you recruit this turn enters play directly.",
   "art": "numeri_drones.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "optio_crusher",
   "name": "Optio Crusher",
   "set": "base",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 5,
   "qty": 2,
   "defense": 4,
   "shield": null,
   "text": "Exhaust: gain 3 power.\nM10: gain 5 instead.",
   "art": "optio_crusher.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "primus_pilus",
   "name": "Primus Pilus",
   "set": "base",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 2,
   "qty": 1,
   "defense": 6,
   "shield": null,
   "text": "Exhaust: if you control three or more Homodeus champions, draw two cards.",
   "art": "primus_pilus.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "additri_gaiamancer",
   "name": "Additri, Gaiamancer",
   "set": "base",
   "faction": "Undergrowth",
   "types": [
    "Champion"
   ],
   "cost": 5,
   "qty": 1,
   "defense": 5,
   "shield": null,
   "text": "Exhaust: gain 2 power, plus 2 more for each Undergrowth ally you played this turn.",
   "art": "additri_gaiamancer.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "giga_source_adept",
   "name": "Giga, Source Adept",
   "set": "base",
   "faction": "Order",
   "types": [
    "Champion"
   ],
   "cost": 2,
   "qty": 1,
   "defense": 4,
   "shield": null,
   "text": "When played, draw a card.\nExhaust — Dominion: gain 3 mastery.",
   "art": "giga_source_adept.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "systema_ai",
   "name": "Systema A.I.",
   "set": "base",
   "faction": "Order",
   "types": [
    "Champion"
   ],
   "cost": 3,
   "qty": 1,
   "defense": 4,
   "shield": null,
   "text": "Exhaust: gain 1 mastery.\nM20: also draw two cards.",
   "art": "systema_ai.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "zetta_encryptor",
   "name": "Zetta, The Encryptor",
   "set": "base",
   "faction": "Order",
   "types": [
    "Champion"
   ],
   "cost": 5,
   "qty": 1,
   "defense": 5,
   "shield": 5,
   "text": "Shield 5.\nYou and your other champions can't be attacked while Zetta is in play.",
   "art": "zetta_encryptor.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "fao_cutul",
   "name": "Fao Cu'tul, The Formless",
   "set": "base",
   "faction": "Wraethe",
   "types": [
    "Champion"
   ],
   "cost": 4,
   "qty": 1,
   "defense": 4,
   "shield": null,
   "text": "Exhaust: gain 2 power.\nM20: then double your power.",
   "art": "fao_cutul.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "li_hin",
   "name": "Li Hin, The Shattered",
   "set": "base",
   "faction": "Wraethe",
   "types": [
    "Champion"
   ],
   "cost": 3,
   "qty": 1,
   "defense": 1,
   "shield": null,
   "text": "Can't be attacked with power. Card effects can still destroy it.\nExhaust: gain 1 power.",
   "art": "li_hin.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "zen_chi_set",
   "name": "Zen Chi Set, Godkiller",
   "set": "base",
   "faction": "Wraethe",
   "types": [
    "Champion"
   ],
   "cost": 7,
   "qty": 1,
   "defense": 5,
   "shield": null,
   "text": "Exhaust: gain 3 power.\nThen return a Wraethe card from your discard pile to your hand.",
   "art": "zen_chi_set.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "venator_of_the_wastes",
   "name": "Venator of the Wastes",
   "set": "base",
   "faction": "Homodeus",
   "types": [
    "Mercenary"
   ],
   "cost": 4,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 4 power.\nInspire: an enemy player loses 2 mastery.",
   "art": "venator_of_the_wastes.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "fungal_hermit",
   "name": "Fungal Hermit",
   "set": "base",
   "faction": "Undergrowth",
   "types": [
    "Mercenary"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 1 mastery.\nM10: gain 5 health. Its own mastery gain counts.",
   "art": "fungal_hermit.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "ghostwillow_avenger",
   "name": "Ghostwillow Avenger",
   "set": "base",
   "faction": "Undergrowth",
   "types": [
    "Mercenary"
   ],
   "cost": 4,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 4 power.\nM15: destroy all enemy champions.",
   "art": "ghostwillow_avenger.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "leshai_knight",
   "name": "Le'shai Knight",
   "set": "base",
   "faction": "Undergrowth",
   "types": [
    "Mercenary"
   ],
   "cost": 3,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 3 power.\nUnify: gain 6 instead.",
   "art": "leshai_knight.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "root_of_the_forest",
   "name": "Root of the Forest",
   "set": "base",
   "faction": "Undergrowth",
   "types": [
    "Mercenary"
   ],
   "cost": 7,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 10 health.\nUnify: gain 10 power.",
   "art": "root_of_the_forest.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "spore_cleric",
   "name": "Spore Cleric",
   "set": "base",
   "faction": "Undergrowth",
   "types": [
    "Mercenary"
   ],
   "cost": 2,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 4 health.",
   "art": "spore_cleric.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "cache_warden",
   "name": "Cache Warden",
   "set": "base",
   "faction": "Order",
   "types": [
    "Mercenary"
   ],
   "cost": 2,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 1 mastery.\nM10: draw a card. Its own mastery gain counts.",
   "art": "cache_warden.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "data_heretic",
   "name": "Data Heretic",
   "set": "base",
   "faction": "Order",
   "types": [
    "Mercenary"
   ],
   "cost": 3,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Draw two cards.",
   "art": "data_heretic.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "grand_architect",
   "name": "The Grand Architect",
   "set": "base",
   "faction": "Order",
   "types": [
    "Mercenary"
   ],
   "cost": 7,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 5 mastery.",
   "art": "grand_architect.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "omnius",
   "name": "Omnius, The All-Knowing",
   "set": "base",
   "faction": "Order",
   "types": [
    "Mercenary"
   ],
   "cost": 6,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Draw two cards.\nDominion: gain 5 mastery.",
   "art": "omnius.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "shard_abstractor",
   "name": "Shard Abstractor",
   "set": "base",
   "faction": "Order",
   "types": [
    "Mercenary"
   ],
   "cost": 3,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 2 mastery.",
   "art": "shard_abstractor.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "aetherbreaker",
   "name": "Aetherbreaker",
   "set": "base",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 4,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 4 power.\nM10: gain 8 instead.",
   "art": "aetherbreaker.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "nil_assassin",
   "name": "Nil Assassin",
   "set": "base",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 2,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 5 power.",
   "art": "nil_assassin.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "scion_of_nothingness",
   "name": "Scion of Nothingness",
   "set": "base",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 5,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 3 power.\nEcho: gain 2 more per Wraethe card.",
   "art": "scion_of_nothingness.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "shadow_apostle",
   "name": "Shadow Apostle",
   "set": "base",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 2,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 2 power.\nYou may banish a card from your hand or discard pile.",
   "art": "shadow_apostle.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "umbral_scourge",
   "name": "Umbral Scourge",
   "set": "base",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 3,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 1 mastery.\nYou may banish a card from your hand or discard pile.",
   "art": "umbral_scourge.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "zara_ra",
   "name": "Zara Ra, Soulflayer",
   "set": "base",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 5,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 4 power and 1 mastery.\nM10: you may banish up to two cards from your hand and/or discard pile.",
   "art": "zara_ra.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "blaster",
   "name": "Blaster",
   "set": "base",
   "faction": "None",
   "types": [
    "Starter"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 1 power.",
   "art": "blaster.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "crystal",
   "name": "Crystal",
   "set": "base",
   "faction": "None",
   "types": [
    "Starter"
   ],
   "cost": 0,
   "qty": 7,
   "defense": null,
   "shield": null,
   "text": "Gain 1 gem.",
   "art": "crystal.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "infinity_shard",
   "name": "Infinity Shard",
   "set": "base",
   "faction": "None",
   "types": [
    "Starter"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 2 power.\nM10: 3 instead.\nM20: 5 instead.\nM30: infinite power.",
   "art": "infinity_shard.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "shard_reactor",
   "name": "Shard Reactor",
   "set": "base",
   "faction": "None",
   "types": [
    "Starter"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 2 gems.\nM5: gain 3 instead.\nM15: gain 4 instead.",
   "art": "shard_reactor.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "limiter_drones",
   "name": "Limiter Drones",
   "set": "relics_of_the_future",
   "faction": "Homodeus",
   "types": [
    "Ally"
   ],
   "cost": 2,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Inspire: you may banish a card from your hand or discard pile.\nDraw a card.",
   "art": "limiter_drones.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "arach_devotees",
   "name": "Arach Devotees",
   "set": "relics_of_the_future",
   "faction": "Undergrowth",
   "types": [
    "Ally"
   ],
   "cost": 2,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Draw a card.\nUnify: gain 3 health.",
   "art": "arach_devotees.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "cloud_oracles",
   "name": "Cloud Oracles",
   "set": "relics_of_the_future",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 2,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Draw a card.\nIf your mastery is higher than every other player's, gain 2 gems.",
   "art": "cloud_oracles.png",
   "artPrompt": "",
   "notes": "Errata: superseded by the Shadow of Salvation printing (cloud_oracles_sos) whenever SoS is enabled."
  },
  {
   "id": "mainframe_abbot",
   "name": "Mainframe Abbot",
   "set": "relics_of_the_future",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": 3,
   "text": "Shield 3.\nDraw a card.\nIf your character is Tetra, gain 1 mastery.",
   "art": "mainframe_abbot.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "pall_shades",
   "name": "Pall Shades",
   "set": "relics_of_the_future",
   "faction": "Wraethe",
   "types": [
    "Ally"
   ],
   "cost": 2,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Echo: gain 3 power.\nDraw a card.",
   "art": "pall_shades.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "axia",
   "name": "Axia",
   "set": "relics_of_the_future",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 7,
   "qty": 1,
   "defense": 7,
   "shield": null,
   "text": "Costs 1 less per Homodeus champion you control.\nExhaust: gain 7 power.",
   "art": "axia.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "ferrata_guard",
   "name": "Ferrata Guard",
   "set": "relics_of_the_future",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 4,
   "qty": 2,
   "defense": 4,
   "shield": null,
   "text": "If your character is Decima, your champions get +2 defense.\nExhaust: gain 1 gem per Homodeus champion you control.",
   "art": "ferrata_guard.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "taur_arachpriest",
   "name": "Taur, Arachpriest",
   "set": "relics_of_the_future",
   "faction": "Undergrowth",
   "types": [
    "Champion"
   ],
   "cost": 5,
   "qty": 1,
   "defense": 4,
   "shield": null,
   "text": "Exhaust: copy the effect of an Undergrowth ally you played this turn.",
   "art": "taur_arachpriest.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "raidian",
   "name": "Raidian, Cloud Master",
   "set": "relics_of_the_future",
   "faction": "Order",
   "types": [
    "Champion"
   ],
   "cost": 5,
   "qty": 1,
   "defense": 3,
   "shield": null,
   "text": "Players with lower mastery than yours can't attack this champion.\nExhaust: draw a card.",
   "art": "raidian.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "ru_bo_vai",
   "name": "Ru Bo Vai, The Transcendant",
   "set": "relics_of_the_future",
   "faction": "Wraethe",
   "types": [
    "Champion"
   ],
   "cost": 5,
   "qty": 1,
   "defense": 4,
   "shield": null,
   "text": "Exhaust: gain 4 power.\nM10: your damage ignores shields this turn.",
   "art": "ru_bo_vai.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "hounds_of_volos",
   "name": "Hounds of Volos",
   "set": "relics_of_the_future",
   "faction": "Undergrowth",
   "types": [
    "Mercenary"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 5 health.\nIf your character is Volos, also gain 5 power.",
   "art": "hounds_of_volos.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "the_lost",
   "name": "The Lost",
   "set": "relics_of_the_future",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 4,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 6 power.\nIf your character is Ko Syn Wu, you may banish a card from your hand or discard pile.",
   "art": "the_lost.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "praetorian_01",
   "name": "Praetorian-01",
   "set": "relics_of_the_future",
   "faction": "Homodeus",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 8 power.\nM20: 12 instead.\nWhile in your discard pile: when you play a champion, return this to your hand.",
   "art": "praetorian_01.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "praetorian_02",
   "name": "Praetorian-02",
   "set": "relics_of_the_future",
   "faction": "Homodeus",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": 9,
   "shield": 3,
   "text": "Relic champion, defense 9.\nWhile in play: shield 3.\nM20: shield 6 instead.\nIts shield never works from hand.",
   "art": "praetorian_02.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "entropic_talons",
   "name": "Entropic Talons",
   "set": "relics_of_the_future",
   "faction": "Undergrowth",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Draw two cards.\nThis turn, gain 1 power per health you gain, even at the 50 health cap.\nM20: also gain 10 health.",
   "art": "entropic_talons.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "panconscious_crown",
   "name": "Panconscious Crown",
   "set": "relics_of_the_future",
   "faction": "Undergrowth",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 2 mastery and 2 health.\nM20 Unify: gain 50 health.",
   "art": "panconscious_crown.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "datic_robes",
   "name": "Datic Robes",
   "set": "relics_of_the_future",
   "faction": "Order",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": 1,
   "text": "Shield equal to your mastery.\nDraw a card.\nM20: draw two instead.",
   "art": "datic_robes.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "terminal_crescents",
   "name": "Terminal Crescents",
   "set": "relics_of_the_future",
   "faction": "Order",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 1 mastery, then power equal to half your mastery, rounded up.\nM20: equal to your full mastery.",
   "art": "terminal_crescents.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "heart_of_nothing",
   "name": "The Heart of Nothing",
   "set": "relics_of_the_future",
   "faction": "Wraethe",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 5 power.\nM20: gain 10 instead.\nIf you deal 10+ unprevented damage to one opponent this turn, draw 3 extra cards at end of turn.",
   "art": "heart_of_nothing.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "world_piercer",
   "name": "The World Piercer",
   "set": "relics_of_the_future",
   "faction": "Wraethe",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 2 mastery.\nReturn a mercenary from your discard pile to your hand.\nM20: return ALL of them.",
   "art": "world_piercer.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "cloud_oracles_sos",
   "name": "Cloud Oracles",
   "set": "shadow_of_salvation",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 2,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Draw a card.\nIf your mastery is higher than every enemy player's, gain 2 gems.",
   "art": "cloud_oracles_sos.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "breaker",
   "name": "Breaker",
   "set": "shadow_of_salvation",
   "faction": "Aion",
   "types": [
    "Ally"
   ],
   "cost": 6,
   "qty": 1,
   "defense": null,
   "shield": 4,
   "text": "Shield 4.\nWhen you recruit this, it goes to your hand instead of your discard pile.\nWarp.",
   "art": "breaker.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "brute",
   "name": "Brute",
   "set": "shadow_of_salvation",
   "faction": "Aion",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": 2,
   "text": "Shield 2.\nGain 4 power.\nWarp 2.",
   "art": "brute.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "dash",
   "name": "Dash",
   "set": "shadow_of_salvation",
   "faction": "Aion",
   "types": [
    "Ally"
   ],
   "cost": 2,
   "qty": 2,
   "defense": null,
   "shield": 2,
   "text": "Shield 2.\nYou may put an Aion card from your discard pile on top of your deck.\nDraw a card.",
   "art": "dash.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "lucky",
   "name": "Lucky",
   "set": "shadow_of_salvation",
   "faction": "Aion",
   "types": [
    "Ally"
   ],
   "cost": 4,
   "qty": 2,
   "defense": null,
   "shield": 2,
   "text": "Shield 2.\nGain 2 gems.\nWarp 3.",
   "art": "lucky.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "swyft",
   "name": "Swyft",
   "set": "shadow_of_salvation",
   "faction": "Aion",
   "types": [
    "Champion"
   ],
   "cost": 5,
   "qty": 2,
   "defense": 3,
   "shield": null,
   "text": "Exhaust: gain 2 gems and 2 power.\nIf your character is Rez, you may keep cards you fast-play. They go to your discard pile.",
   "art": "swyft.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "slipstream_shard",
   "name": "Slipstream Shard",
   "set": "shadow_of_salvation",
   "faction": "Aion",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 1 mastery and draw a card.\nM20: take an extra turn. Once per game.",
   "art": "slipstream_shard.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "warpquartz",
   "name": "Warpquartz",
   "set": "shadow_of_salvation",
   "faction": "Aion",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 3 gems and 3 power.\nM20: banish up to 3 allies from your hand/discard and gain their effects.",
   "art": "warpquartz.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "legion_carrier",
   "name": "Legion Carrier",
   "set": "into_the_horizon",
   "faction": "Homodeus",
   "types": [
    "Ally"
   ],
   "cost": 2,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 2 gems.\nReveal your deck's top 3 cards: up to one revealed champion to your hand, the rest to your discard pile.",
   "art": "legion_carrier.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "torian_commandos",
   "name": "Torian Commandos",
   "set": "into_the_horizon",
   "faction": "Homodeus",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 3,
   "defense": null,
   "shield": 4,
   "text": "Shield 4.\nGain 2 gems and 2 power.",
   "art": "torian_commandos.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "anomaly_cleric",
   "name": "Anomaly Cleric",
   "set": "into_the_horizon",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 5,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 3 gems and 1 mastery.\nM10: the next card you recruit this turn goes to your hand.",
   "art": "anomaly_cleric.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "duplication_fabricator",
   "name": "Duplication Fabricator",
   "set": "into_the_horizon",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 1,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 1 mastery.\nEvery player reveals their deck's top card; copy the effect of one revealed ally.",
   "art": "duplication_fabricator.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "shard_seer",
   "name": "Shard Seer",
   "set": "into_the_horizon",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 2,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Draw a card.\nYou may reveal an Infinity Shard from your hand to gain 2 mastery.",
   "art": "shard_seer.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "the_dispossessed",
   "name": "The Dispossessed",
   "set": "into_the_horizon",
   "faction": "Wraethe",
   "types": [
    "Ally"
   ],
   "cost": 1,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 3 power.\nWhile in your discard pile: when you play a Wraethe card, you may return this to your hand.",
   "art": "the_dispossessed.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "g_48",
   "name": "G-48",
   "set": "into_the_horizon",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 4,
   "qty": 1,
   "defense": 5,
   "shield": null,
   "text": "Exhaust: reset another champion you control. It may exhaust again this turn.",
   "art": "g_48.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "orm_madu",
   "name": "Orm Madu",
   "set": "into_the_horizon",
   "faction": "Undergrowth",
   "types": [
    "Champion"
   ],
   "cost": 7,
   "qty": 1,
   "defense": 7,
   "shield": null,
   "text": "Exhaust: gain 7 health.\nThen, if you are at 50 health, gain 1 mastery.",
   "art": "orm_madu.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "oblivion_gatekeeper",
   "name": "Oblivion Gatekeeper",
   "set": "into_the_horizon",
   "faction": "Wraethe",
   "types": [
    "Champion"
   ],
   "cost": 4,
   "qty": 1,
   "defense": 5,
   "shield": null,
   "text": "Exhaust: reveal your deck's top card, lose health equal to its cost, and put it into your hand. This is a loss, not damage — shields can't prevent it.\nM20: every opponent loses that health instead.",
   "art": "oblivion_gatekeeper.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "j_chord",
   "name": "J-Chord",
   "set": "into_the_horizon",
   "faction": "Aion",
   "types": [
    "Champion"
   ],
   "cost": 3,
   "qty": 1,
   "defense": 3,
   "shield": null,
   "text": "Exhaust — Warp 3.\nM15: Warp 5 instead.",
   "art": "j_chord.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "carnivorous_vine",
   "name": "Carnivorous Vine",
   "set": "into_the_horizon",
   "faction": "Undergrowth",
   "types": [
    "Mercenary"
   ],
   "cost": 4,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 3 health and 3 power.\nGain 2 more health and 2 more power per OTHER Undergrowth ally you played this turn.",
   "art": "carnivorous_vine.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "the_rotten",
   "name": "The Rotten",
   "set": "into_the_horizon",
   "faction": "Undergrowth",
   "types": [
    "Mercenary"
   ],
   "cost": 3,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 5 power and 1 mastery.",
   "art": "the_rotten.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "cinder_scars",
   "name": "Cinder Scars",
   "set": "into_the_horizon",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 2,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Draw a card.\nIf you played another Cinder Scars this turn, gain 3 power.\nM10: you may banish a card from your hand or discard pile.",
   "art": "cinder_scars.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "ingeminex_agony",
   "name": "Ingeminex: Agony",
   "set": "into_the_horizon",
   "faction": "Monster",
   "types": [
    "Monster"
   ],
   "cost": 0,
   "qty": 1,
   "defense": 10,
   "shield": null,
   "text": "Attack: every player discards 2 cards.\nReward: draw 2 cards and take an additional destiny.",
   "art": "ingeminex_agony.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "ingeminex_brutality",
   "name": "Ingeminex: Brutality",
   "set": "into_the_horizon",
   "faction": "Monster",
   "types": [
    "Monster"
   ],
   "cost": 0,
   "qty": 1,
   "defense": 10,
   "shield": null,
   "text": "Attack: every player loses 5 health.\nReward: gain 20 health.",
   "art": "ingeminex_brutality.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "ingeminex_corruption",
   "name": "Ingeminex: Corruption",
   "set": "into_the_horizon",
   "faction": "Monster",
   "types": [
    "Monster"
   ],
   "cost": 0,
   "qty": 1,
   "defense": 10,
   "shield": null,
   "text": "Attack: every player loses 3 health and 1 mastery.\nReward: recruit an additional relic to your hand.",
   "art": "ingeminex_corruption.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "ingeminex_malice",
   "name": "Ingeminex: Malice",
   "set": "into_the_horizon",
   "faction": "Monster",
   "types": [
    "Monster"
   ],
   "cost": 0,
   "qty": 1,
   "defense": 10,
   "shield": null,
   "text": "Attack: every player destroys their highest-cost champion.\nReward: return a champion from your discard pile to your hand and take an additional destiny.",
   "art": "ingeminex_malice.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "ingeminex_torment",
   "name": "Ingeminex: Torment",
   "set": "into_the_horizon",
   "faction": "Monster",
   "types": [
    "Monster"
   ],
   "cost": 0,
   "qty": 1,
   "defense": 10,
   "shield": null,
   "text": "Attack: every player loses 2 mastery.\nReward: gain 4 mastery.",
   "art": "ingeminex_torment.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "absorption_grid",
   "name": "Absorption Grid",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: gain 2 power per shield ally you played this turn.",
   "art": "absorption_grid.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "advanced_medicine",
   "name": "Advanced Medicine",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played 2+ even-cost cards this turn, gain 4 health.\nCost-less cards are neither even nor odd.",
   "art": "advanced_medicine.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "advanced_weapons",
   "name": "Advanced Weapons",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played 2+ odd-cost cards this turn, gain 3 power.\nCost-less cards are neither even nor odd.",
   "art": "advanced_weapons.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "agony_of_choice",
   "name": "The Agony of Choice",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played cards of 3+ different factions this turn, gain 4 power.",
   "art": "agony_of_choice.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "biotech_enhancements",
   "name": "Biotech Enhancements",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played a Homodeus card and an Undergrowth card this turn, draw a card.",
   "art": "biotech_enhancements.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "blood_for_blood",
   "name": "Blood for Blood",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "When you deal 5+ unblocked damage to an opponent, you may banish a card you played this turn.",
   "art": "blood_for_blood.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "bound_for_life",
   "name": "Bound for Life",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: ALL players lose 4 health, including you. Not damage — shields can't prevent it.",
   "art": "bound_for_life.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "crystal_gate",
   "name": "The Crystal Gate",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played an Order card and an Undergrowth card this turn, recruit a card costing 3 or less for free.",
   "art": "crystal_gate.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "datic_secrets",
   "name": "Datic Secrets",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played 2+ Order allies this turn, gain 2 gems.",
   "art": "datic_secrets.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "deadly_recruits",
   "name": "Deadly Recruits",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: fast-play a cost-1 ally from the row for free. You keep it.\nM20: cost 2 or less.",
   "art": "deadly_recruits.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "forged_in_flame",
   "name": "Forged in Flame",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played a Wraethe card and a Homodeus card this turn, banish a card from your hand or discard pile.",
   "art": "forged_in_flame.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "healing_hands",
   "name": "Healing Hands",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played a champion this turn, gain 4 health.",
   "art": "healing_hands.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "maglev_tunnels",
   "name": "Maglev Tunnels",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "When you recruit a Homodeus champion, you may put it on top of your deck.",
   "art": "maglev_tunnels.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "nature_dominance",
   "name": "Nature Dominance",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: gain 1 health and 1 power per Undergrowth card you played this turn.",
   "art": "nature_dominance.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "one_mind_one_army",
   "name": "One Mind One Army",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Your champions get +2 defense.",
   "art": "one_mind_one_army.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "paradigm_shift",
   "name": "Paradigm Shift",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played an Order card and a Wraethe card this turn, gain 1 mastery.",
   "art": "paradigm_shift.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "phasic_technology",
   "name": "Phasic Technology",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Your Homodeus and Order cards get +2 shield.",
   "art": "phasic_technology.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "power_struggle",
   "name": "Power Struggle",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: destroy a champion you control to gain 5 power.",
   "art": "power_struggle.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "price_of_power",
   "name": "The Price of Power",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: gain 1 power per Wraethe card in your discard pile.",
   "art": "price_of_power.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "project_yggdrasil",
   "name": "Project Yggdrasil",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Your Wraethe cards also count as Undergrowth and vice versa.",
   "art": "project_yggdrasil.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "shard_defiant",
   "name": "The Shard Defiant",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Pay 2 gems, Exhaust: reveal the center deck's top card; recruit or banish it.\nIf you played an Aion card this turn, you may repeat this once.",
   "art": "shard_defiant.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "soul_syphon",
   "name": "Soul Syphon",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played cards of 3+ different factions this turn, gain 5 health.",
   "art": "soul_syphon.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "stolen_futures",
   "name": "Stolen Futures",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "M10 — Exhaust: banish this destiny; add 2 destinies from the deck to the row, then take 2 destinies.",
   "art": "stolen_futures.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "strategic_mastermind",
   "name": "Strategic Mastermind",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you have 40 or more health, draw a card.",
   "art": "strategic_mastermind.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "synthesis",
   "name": "Synthesis",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "M15 — Exhaust: draw a card.",
   "art": "synthesis.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "the_last_city",
   "name": "The Last City",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played 2+ mercenaries this turn, gain 2 gems.",
   "art": "the_last_city.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "true_leader",
   "name": "True Leader",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played 3 cards of the same faction this turn, gain 2 mastery.",
   "art": "true_leader.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "unconditional_conscription",
   "name": "Unconditional Conscription",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played 2+ non-starter allies costing 2 or less this turn, gain 4 power.",
   "art": "unconditional_conscription.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "war_bound",
   "name": "War Bound",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you control 2+ champions, gain 4 power.",
   "art": "war_bound.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "whatever_it_takes",
   "name": "Whatever it Takes",
   "set": "into_the_horizon",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Pay 6 gems, Exhaust: gain 9 power.",
   "art": "whatever_it_takes.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "century_forge",
   "name": "Century Forge",
   "set": "duel",
   "faction": "Homodeus",
   "types": [
    "Ally"
   ],
   "cost": 5,
   "qty": 2,
   "defense": null,
   "shield": 3,
   "text": "Shield 3. Gain 3 gems.\nInspire: the next champion you recruit this turn enters play directly.",
   "art": "century_forge.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "korvus_legionnaire_duel",
   "name": "Korvus Legionnaire",
   "set": "duel",
   "faction": "Homodeus",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 3,
   "defense": null,
   "shield": 2,
   "text": "Shield 2. Gain 3 power.\nReturn a champion from your discard pile to your hand.",
   "art": "korvus_legionnaire_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "legion_carrier_duel",
   "name": "Legion Carrier",
   "set": "duel",
   "faction": "Homodeus",
   "types": [
    "Ally"
   ],
   "cost": 2,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 2 gems.\nReveal your deck's top 5 cards: up to one revealed champion to your hand, the rest to your discard pile.",
   "art": "legion_carrier_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "reactor_drone_duel",
   "name": "Reactor Drone",
   "set": "duel",
   "faction": "Homodeus",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 3,
   "defense": null,
   "shield": 2,
   "text": "Choose one:\n— Gain 2 gems.\n— Gain 3 gems, then banish this card at the end of your turn.",
   "art": "reactor_drone_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "furrowing_elemental_duel",
   "name": "Furrowing Elemental",
   "set": "duel",
   "faction": "Undergrowth",
   "types": [
    "Ally"
   ],
   "cost": 5,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 4 health and draw a card.\nIf you are at 50 health, gain 4 power.",
   "art": "furrowing_elemental_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "nectar_alchemist",
   "name": "Nectar Alchemist",
   "set": "duel",
   "faction": "Undergrowth",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 4 health.\nThis turn, health you would gain beyond the 50 cap becomes power instead.",
   "art": "nectar_alchemist.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "shardwood_guardian_duel",
   "name": "Shardwood Guardian",
   "set": "duel",
   "faction": "Undergrowth",
   "types": [
    "Ally"
   ],
   "cost": 4,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 2 power and draw a card.\nUnify: gain 4 health.",
   "art": "shardwood_guardian_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "undergrowth_aspirant_duel",
   "name": "Undergrowth Aspirant",
   "set": "duel",
   "faction": "Undergrowth",
   "types": [
    "Ally"
   ],
   "cost": 1,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 3 health.\nUnify: also gain 4 power.",
   "art": "undergrowth_aspirant_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "bulwark_chanter",
   "name": "Bulwark Chanter",
   "set": "duel",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 4,
   "qty": 2,
   "defense": null,
   "shield": 4,
   "text": "Shield 4. Gain 2 gems.\nDominion: gain 2 mastery and draw a card.",
   "art": "bulwark_chanter.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "command_seer_duel",
   "name": "Command Seer",
   "set": "duel",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 4,
   "qty": 2,
   "defense": null,
   "shield": 5,
   "text": "Shield 5. Gain 3 gems.",
   "art": "command_seer_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "duplication_fabricator_duel",
   "name": "Duplication Fabricator",
   "set": "duel",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 1 mastery.\nEvery player reveals their deck's top card; copy the effect of one revealed ally.\nM20: you may copy any number of effects from the revealed cards instead.",
   "art": "duplication_fabricator_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "index_of_futures",
   "name": "Index of Futures",
   "set": "duel",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": 2,
   "text": "Shield 2. Draw a card. Look at the center deck's top 3 cards; put them back in any order.",
   "art": "index_of_futures.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "mainframe_abbot_duel",
   "name": "Mainframe Abbot",
   "set": "duel",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": 3,
   "text": "Shield 3. Draw a card.\nAllegiance Order 4: gain 1 mastery.",
   "art": "mainframe_abbot_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "order_initiate_duel",
   "name": "Order Initiate",
   "set": "duel",
   "faction": "Order",
   "types": [
    "Ally"
   ],
   "cost": 1,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "You may remove a card from the shop. Gain 2 gems. Dominion: gain 2 mastery.",
   "art": "order_initiate_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "whisper_extractor",
   "name": "Whisper Extractor",
   "set": "duel",
   "faction": "Wraethe",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 2 power.\nTarget opponent draws a card, then choose a card in their hand — they discard it.",
   "art": "whisper_extractor.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "wraethe_skirmisher_duel",
   "name": "Wraethe Skirmisher",
   "set": "duel",
   "faction": "Wraethe",
   "types": [
    "Ally"
   ],
   "cost": 1,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 2 power.\nEcho: gain 5 instead.",
   "art": "wraethe_skirmisher_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "comet",
   "name": "Comet",
   "set": "duel",
   "faction": "Aion",
   "types": [
    "Ally"
   ],
   "cost": 14,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Destroy target opponent.\nCannot be fast-played — it must be bought with gems.\nCannot be removed from the shop.",
   "art": "comet.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "dash_duel",
   "name": "Dash",
   "set": "duel",
   "faction": "Aion",
   "types": [
    "Ally"
   ],
   "cost": 2,
   "qty": 2,
   "defense": null,
   "shield": 2,
   "text": "Shield 2.\nYou may put an Aion card from your discard pile on top of your deck.\nM10: any card instead.\nDraw a card.",
   "art": "dash_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "longshot",
   "name": "Longshot",
   "set": "duel",
   "faction": "Aion",
   "types": [
    "Ally"
   ],
   "cost": 4,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Reveal the top 2 cards of the center deck.\nYou may fast-play any of them that are allies costing 3 or less; the rest go under the center deck.\nM15: cost 5 or less instead.",
   "art": "longshot.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "prism",
   "name": "Prism",
   "set": "duel",
   "faction": "Aion",
   "types": [
    "Ally"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": 2,
   "text": "Shield 2. Draw a card. This card counts as a card of every faction.",
   "art": "prism.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "axia_duel",
   "name": "Axia",
   "set": "duel",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 8,
   "qty": 1,
   "defense": 7,
   "shield": null,
   "text": "Costs 1 less per Homodeus champion you control.\nExhaust: gain 7 power.",
   "art": "axia_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "evokatus_duel",
   "name": "Evokatus",
   "set": "duel",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 4,
   "qty": 2,
   "defense": 2,
   "shield": null,
   "text": "When played, draw a card.\nExhaust: gain 1 power per champion you control.",
   "art": "evokatus_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "ferrata_guard_duel",
   "name": "Ferrata Guard",
   "set": "duel",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 4,
   "qty": 2,
   "defense": 4,
   "shield": null,
   "text": "Allegiance Homodeus 4: your champions get +2 defense.\nExhaust: gain 1 gem per Homodeus champion you control.",
   "art": "ferrata_guard_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "primus_pilus_duel",
   "name": "Primus Pilus",
   "set": "duel",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 2,
   "qty": 1,
   "defense": 5,
   "shield": null,
   "text": "Exhaust: if you control three or more champions, draw two cards.",
   "art": "primus_pilus_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "testudo_vanguard",
   "name": "Testudo Vanguard",
   "set": "duel",
   "faction": "Homodeus",
   "types": [
    "Champion"
   ],
   "cost": 4,
   "qty": 2,
   "defense": 6,
   "shield": null,
   "text": "Your shields are also applied to each of your champions individually.\nExhaust: gain 2 gems.",
   "art": "testudo_vanguard.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "orm_madu_duel",
   "name": "Orm Madu",
   "set": "duel",
   "faction": "Undergrowth",
   "types": [
    "Champion"
   ],
   "cost": 7,
   "qty": 1,
   "defense": 7,
   "shield": null,
   "text": "Exhaust: gain 6 health.\nIf you are then at 50 health, gain 1 mastery.",
   "art": "orm_madu_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "thornshell_warden",
   "name": "Thornshell Warden",
   "set": "duel",
   "faction": "Undergrowth",
   "types": [
    "Champion"
   ],
   "cost": 2,
   "qty": 2,
   "defense": 6,
   "shield": null,
   "text": "Exhaust: gain 2 health.\nIf you are at 50 health, also gain 2 power.",
   "art": "thornshell_warden.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "aegis_archivist",
   "name": "Aegis Archivist",
   "set": "duel",
   "faction": "Order",
   "types": [
    "Champion"
   ],
   "cost": 4,
   "qty": 1,
   "defense": 5,
   "shield": null,
   "text": "Exhaust: gain 2 gems.\nDominion: gain 5 gems instead.",
   "art": "aegis_archivist.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "li_hin_duel",
   "name": "Li Hin, The Shattered",
   "set": "duel",
   "faction": "Wraethe",
   "types": [
    "Champion"
   ],
   "cost": 3,
   "qty": 1,
   "defense": 1,
   "shield": null,
   "text": "Can't be attacked with power. Card effects can still destroy it.\nExhaust: gain 2 power.",
   "art": "li_hin_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "ru_bo_vai_duel",
   "name": "Ru Bo Vai, The Transcendant",
   "set": "duel",
   "faction": "Wraethe",
   "types": [
    "Champion"
   ],
   "cost": 5,
   "qty": 1,
   "defense": 4,
   "shield": null,
   "text": "Exhaust: gain 3 power.\nM10: your damage ignores shields this turn.",
   "art": "ru_bo_vai_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "j_chord_duel",
   "name": "J-Chord",
   "set": "duel",
   "faction": "Aion",
   "types": [
    "Champion"
   ],
   "cost": 3,
   "qty": 1,
   "defense": 3,
   "shield": null,
   "text": "Exhaust — Warp 3.\nM15: Warp 6 instead.",
   "art": "j_chord_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "swyft_duel",
   "name": "Swyft",
   "set": "duel",
   "faction": "Aion",
   "types": [
    "Champion"
   ],
   "cost": 5,
   "qty": 2,
   "defense": 3,
   "shield": null,
   "text": "Exhaust: gain 2 gems and 2 power.\nM10: you may keep cards you fast-play — they join your discard.",
   "art": "swyft_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "riposte_doctrine",
   "name": "Riposte Doctrine",
   "set": "duel",
   "faction": "Homodeus",
   "types": [
    "Mercenary"
   ],
   "cost": 2,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 3 power.\nIf you played or reveal a shield card from your hand, gain 6 power instead.",
   "art": "riposte_doctrine.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "hounds_of_volos_duel",
   "name": "Hounds of Volos",
   "set": "duel",
   "faction": "Undergrowth",
   "types": [
    "Mercenary"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 5 health.\nAllegiance Undergrowth 4: also gain 5 power.",
   "art": "hounds_of_volos_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "lifebloom_ritual",
   "name": "Lifebloom Ritual",
   "set": "duel",
   "faction": "Undergrowth",
   "types": [
    "Mercenary"
   ],
   "cost": 6,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Until end of turn, all healing you receive is doubled.\nUnify: gain 4 health.",
   "art": "lifebloom_ritual.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "root_of_the_forest_duel",
   "name": "Root of the Forest",
   "set": "duel",
   "faction": "Undergrowth",
   "types": [
    "Mercenary"
   ],
   "cost": 7,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 8 health.\nUnify: gain 8 power.",
   "art": "root_of_the_forest_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "spore_cleric_duel",
   "name": "Spore Cleric",
   "set": "duel",
   "faction": "Undergrowth",
   "types": [
    "Mercenary"
   ],
   "cost": 2,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 3 health.\nUnify: gain 6 health instead.",
   "art": "spore_cleric_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "the_rotten_duel",
   "name": "The Rotten",
   "set": "duel",
   "faction": "Undergrowth",
   "types": [
    "Mercenary"
   ],
   "cost": 3,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 4 power and 1 mastery.",
   "art": "the_rotten_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "data_heretic_duel",
   "name": "Data Heretic",
   "set": "duel",
   "faction": "Order",
   "types": [
    "Mercenary"
   ],
   "cost": 4,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Draw two cards.",
   "art": "data_heretic_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "bleak_communion",
   "name": "Bleak Communion",
   "set": "duel",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Lose 4 health — a loss, not damage.\nDraw two cards.\nEcho: an opponent loses that health instead of you.",
   "art": "bleak_communion.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "cinder_scars_duel",
   "name": "Cinder Scars",
   "set": "duel",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 2,
   "qty": 5,
   "defense": null,
   "shield": null,
   "text": "Draw a card.\nIf you played another Cinder Scars this turn, gain 3 power.\nM10: you may banish a card from your hand or discard pile.",
   "art": "cinder_scars_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "doomstalker",
   "name": "Doomstalker",
   "set": "duel",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 5,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 5 power.\nIf an Ingeminex is in play, gain 8 instead.",
   "art": "doomstalker.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "grim_tutor",
   "name": "Grim Tutor",
   "set": "duel",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 3,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Search your draw pile for a card and put it into your hand, then shuffle.\nYou lose 3 health.",
   "art": "grim_tutor.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "nil_assassin_duel",
   "name": "Nil Assassin",
   "set": "duel",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 2,
   "qty": 3,
   "defense": null,
   "shield": null,
   "text": "Gain 4 power.",
   "art": "nil_assassin_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "the_lost_duel",
   "name": "The Lost",
   "set": "duel",
   "faction": "Wraethe",
   "types": [
    "Mercenary"
   ],
   "cost": 4,
   "qty": 2,
   "defense": null,
   "shield": null,
   "text": "Gain 5 power.\nAllegiance Wraethe 4: you may banish a card from your hand or discard pile.",
   "art": "the_lost_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "praetorian_02_duel",
   "name": "Praetorian-02",
   "set": "duel",
   "faction": "Homodeus",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": 9,
   "shield": 3,
   "text": "While in play: shield 3.\nM20: shield 6 instead.\nExhaust, pay 3 gems: until your next turn, your shields are doubled. Killing this champion does not remove this effect.",
   "art": "praetorian_02_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "praetorian_03",
   "name": "Praetorian-03",
   "set": "duel",
   "faction": "Homodeus",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": 4,
   "text": "Gain 1 mastery and draw a card. M15: 2 mastery and 2 cards instead. M25: 3 mastery and 3 cards instead.",
   "art": "praetorian_03.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "unknown_god",
   "name": "Unknown God",
   "set": "duel",
   "faction": "Undergrowth",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": 5,
   "shield": null,
   "text": "Exhaust: gain 5 health for each champion you control.\nM20: your Exhaust effects apply twice.",
   "art": "unknown_god.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "datic_robes_duel",
   "name": "Datic Robes",
   "set": "duel",
   "faction": "Order",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": 1,
   "text": "Shield equal to your mastery. Draw two cards.\nM20: while this card is in your discard pile, you have shield equal to half your mastery, rounded up.",
   "art": "datic_robes_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "multitask_brain",
   "name": "Multitask Brain",
   "set": "duel",
   "faction": "Order",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "For each different faction you played this turn, gain 2 power and draw a card.\nM20: gain 4 power instead of 2.\nDominion: gain 3 mastery.",
   "art": "multitask_brain.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "terminal_crescents_duel",
   "name": "Terminal Crescents",
   "set": "duel",
   "faction": "Order",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 2 mastery, then power equal to half your mastery, rounded up.\nM20: equal to your full mastery.",
   "art": "terminal_crescents_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "doom_gate",
   "name": "Doom Gate",
   "set": "duel",
   "faction": "Wraethe",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": 6,
   "shield": null,
   "text": "You are unaffected by Ingeminex attacks.\nWhen you play this champion, shuffle 30 new Ingeminex into the center deck. Once per game.\nExhaust: destroy an Ingeminex.",
   "art": "doom_gate.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "heart_of_nothing_duel",
   "name": "The Heart of Nothing",
   "set": "duel",
   "faction": "Wraethe",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 6 power.\nM20: gain 10 instead.\nIf you deal 10+ unprevented damage to one opponent this turn, draw 3 extra cards at end of turn.",
   "art": "heart_of_nothing_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "world_piercer_duel",
   "name": "The World Piercer",
   "set": "duel",
   "faction": "Wraethe",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 2 mastery.\nReturn a mercenary from your discard or draw pile to your hand.\nM20: return ALL of them.",
   "art": "world_piercer_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "slipstream_shard_duel",
   "name": "Slipstream Shard",
   "set": "duel",
   "faction": "Aion",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Gain 2 mastery and draw two cards.\nM20: take an extra turn. Once per game.",
   "art": "slipstream_shard_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "star_seeker",
   "name": "Star Seeker",
   "set": "duel",
   "faction": "Aion",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": 7,
   "shield": null,
   "text": "Exhaust: Warp ∞. M20: Warp ∞ a second time.",
   "art": "star_seeker.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "warpquartz_duel",
   "name": "Warpquartz",
   "set": "duel",
   "faction": "Aion",
   "types": [
    "Relic"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "You may banish a card from your hand or discard pile to gain its effect.\nM20: up to 3 cards instead.\nGain 3 gems and 3 power for each card you banished this turn.",
   "art": "warpquartz_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "agony_of_choice_duel",
   "name": "The Agony of Choice",
   "set": "duel",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played cards of 3+ different factions this turn, gain 5 power.",
   "art": "agony_of_choice_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "datic_secrets_duel",
   "name": "Datic Secrets",
   "set": "duel",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played 2+ Order allies this turn, gain 1 gem and 1 mastery.",
   "art": "datic_secrets_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "deadly_recruits_duel",
   "name": "Deadly Recruits",
   "set": "duel",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: fast-play a cost-2 or less ally from the row for free. You may keep it.\nM20: cost 4 or less.",
   "art": "deadly_recruits_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "healing_hands_duel",
   "name": "Healing Hands",
   "set": "duel",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played a champion this turn, gain 5 health.",
   "art": "healing_hands_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "paradigm_shift_duel",
   "name": "Paradigm Shift",
   "set": "duel",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played an Order card and a Wraethe card this turn, gain 1 gem and 1 mastery.",
   "art": "paradigm_shift_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "soul_syphon_duel",
   "name": "Soul Syphon",
   "set": "duel",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played cards of 3+ different factions this turn, gain 7 health.",
   "art": "soul_syphon_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "the_last_city_duel",
   "name": "The Last City",
   "set": "duel",
   "faction": "None",
   "types": [
    "Destiny"
   ],
   "cost": 0,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Exhaust: if you played 2+ mercenaries this turn, gain 3 gems.",
   "art": "the_last_city_duel.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "soichar_decima",
   "name": "Decima",
   "set": "base",
   "faction": "Homodeus",
   "types": [
    "Character"
   ],
   "cost": null,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Focus — Exhaust: pay 1 gem, gain 1 mastery (once per turn).",
   "art": "soichar_decima.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "soichar_tetra",
   "name": "Tetra",
   "set": "base",
   "faction": "Order",
   "types": [
    "Character"
   ],
   "cost": null,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Focus — Exhaust: pay 1 gem, gain 1 mastery (once per turn).",
   "art": "soichar_tetra.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "soichar_volos",
   "name": "Volos",
   "set": "base",
   "faction": "Undergrowth",
   "types": [
    "Character"
   ],
   "cost": null,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Focus — Exhaust: pay 1 gem, gain 1 mastery (once per turn).",
   "art": "soichar_volos.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "soichar_kosynwu",
   "name": "Ko Syn Wu",
   "set": "base",
   "faction": "Wraethe",
   "types": [
    "Character"
   ],
   "cost": null,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Focus — Exhaust: pay 1 gem, gain 1 mastery (once per turn).",
   "art": "soichar_kosynwu.png",
   "artPrompt": "",
   "notes": ""
  },
  {
   "id": "soichar_rez",
   "name": "Rez",
   "set": "shadow_of_salvation",
   "faction": "Aion",
   "types": [
    "Character"
   ],
   "cost": null,
   "qty": 1,
   "defense": null,
   "shield": null,
   "text": "Focus — Exhaust: pay 1 gem, gain 1 mastery (once per turn).",
   "art": "soichar_rez.png",
   "artPrompt": "",
   "notes": ""
  }
 ]
};
