$ErrorActionPreference='Continue'
$pattern='pascension|shards|ollama|training|train_ai|nvidia-smi'
$tasks=@(Get-ScheduledTask | Where-Object {($_.TaskName+' '+($_.Actions.Execute -join ' ')+' '+($_.Actions.Arguments -join ' ')) -match $pattern} | ForEach-Object { @{name=$_.TaskName;path=$_.TaskPath;state=[string]$_.State;executables=@($_.Actions.Execute);script_paths=@([regex]::Matches(($_.Actions.Arguments -join ' '),'(?i)[A-Za-z]:\\[^"\r\n]*?\.(?:py|ps1|cmd|bat)(?=["\s]|$)') | ForEach-Object {$_.Value})} })
$startup=@(Get-CimInstance Win32_StartupCommand | Where-Object {($_.Name+' '+$_.Command) -match $pattern} | ForEach-Object { @{name=$_.Name;location=$_.Location;script_paths=@([regex]::Matches($_.Command,'(?i)[A-Za-z]:\\[^"\r\n]*?\.(?:exe|py|ps1|cmd|bat)(?=["\s]|$)') | ForEach-Object {$_.Value})} })
$layers=@();foreach($key in @('HKCU:\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers','HKLM:\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers')){if(Test-Path $key){$layers+=@((Get-ItemProperty $key).PSObject.Properties | Where-Object {$_.Name -match 'pascension'} | ForEach-Object {@{path=$_.Name;flags=$_.Value}})}}
$game=@(Get-Process -Name pascension -ErrorAction SilentlyContinue | ForEach-Object {@{pid=$_.Id;responding=$_.Responding;path=$_.Path;modules=@($_.Modules | ForEach-Object {$_.FileName})}})
$recent=@(Get-WinEvent -FilterHashtable @{LogName='Application';StartTime=(Get-Date).AddDays(-14);Id=1000,1001,1002} -MaxEvents 200 -ErrorAction SilentlyContinue | Where-Object {$_.Message -match 'pascension'} | ForEach-Object {@{time=$_.TimeCreated.ToString('o');id=$_.Id;message=$_.Message}})
@{tasks=$tasks;startup=$startup;compatibility=$layers;game=$game;events=$recent} | ConvertTo-Json -Depth 7 | Set-Content -Encoding UTF8 'F:\Unity\projects\pascension\Tools\Diagnostics\game-environment.json'
@{task_count=$tasks.Count;startup_count=$startup.Count;compatibility=$layers;game_count=$game.Count;event_count=$recent.Count} | ConvertTo-Json -Depth 5
